import { MRT_Column } from 'material-react-table';

export interface ColumnInstanceAPI {
  columnInstanceAPI: keyof MRT_Column;
  link?: string;
  linkText?: string;
  description?: string;
  type?: string;
}

export const columnInstanceAPIs: ColumnInstanceAPI[] = [
  {
    columnInstanceAPI: 'accessorFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'clearSorting',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'columnDef',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'columns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'depth',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAggregationFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoAggregationFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoSortDir',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoSortingFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanGlobalFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanGroup',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanHide',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanMultiSort',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanPin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanResize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanSort',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedMinMaxValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedUniqueValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFirstSortDir',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFlatColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getGroupedIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsFiltered',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsGrouped',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsPinned',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsResizing',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsSorted',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsVisible',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getNextSortingOrder',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getPinnedIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSortIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSortingFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getStart',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleGroupingHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleSortingHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleVisibilityHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'id',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'parent',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'pin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'resetSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'setFilterValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleGrouping',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleSorting',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleVisibility',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
];
