import { type MRT_Column } from 'material-react-table';

export interface ColumnInstanceAPI {
  columnInstanceAPI: keyof MRT_Column<ColumnInstanceAPI>;
  link?: string;
  linkText?: string;
  description?: string;
  type?: string;
}

export const columnInstanceAPIs: ColumnInstanceAPI[] = [
  {
    columnInstanceAPI: 'accessorFn',
    type: 'AccessorFn<TData>',
    description:
      'The resolved accessor function to use when extracting the value for the column from each row.',
    link: 'https://tanstack.com/table/v8/docs/api/core/column#accessorfn',
    linkText: 'TanStack Table Column API Docs',
  },
  {
    columnInstanceAPI: 'clearSorting',
    type: '() => void',
    description: "Removes this column from the table's sorting state.",
    link: 'https://tanstack.com/table/v8/docs/api/features/sorting#clearsorting',
    linkText: 'TanStack Table Sorting API Docs',
  },
  {
    columnInstanceAPI: 'columnDef',
    type: 'ColumnDef<TData>',
    description: 'The original column def used to create the column.',
    link: 'https://tanstack.com/table/v8/docs/api/core/column#columndef',
    linkText: 'TanStack Table Column API Docs',
  },
  {
    columnInstanceAPI: 'columns',
    type: 'MRT_ColumnDef<TData>[]',
    description: 'The child column (if the column is a group column).',
    link: 'https://tanstack.com/table/v8/docs/api/core/column#columns',
    linkText: 'TanStack Table Column API Docs',
  },
  {
    columnInstanceAPI: 'depth',
    type: 'number',
    description:
      'The depth of the column (if grouped) relative to the root column def array.',
    link: 'https://tanstack.com/table/v8/docs/api/core/column#depth',
    linkText: 'TanStack Table Column API Docs',
  },
  {
    columnInstanceAPI: 'getAggregationFn',
    type: '() => AggregationFn<TData> | undefined',
    description:
      'Returns the aggregation function (either user-defined or automatic, depending on configuration).',
    link: 'https://tanstack.com/table/v8/docs/api/features/grouping#getaggregationfn',
    linkText: 'TanStack Table Grouping API Docs',
  },
  {
    columnInstanceAPI: 'getAggregationFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoAggregationFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoSortDir',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAutoSortingFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanGlobalFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanGroup',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanHide',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanMultiSort',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanPin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanResize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getCanSort',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedMinMaxValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFacetedUniqueValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFilterValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFirstSortDir',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getFlatColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getGroupedIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsFiltered',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsGrouped',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsPinned',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsResizing',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsSorted',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsVisible',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getNextSortingOrder',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getPinnedIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSortIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getSortingFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getStart',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getAfter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsFirstColumn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getIsLastColumn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleGroupingHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleSortingHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'getToggleVisibilityHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'id',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'parent',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'pin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'resetSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'setFilterValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleGrouping',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleSorting',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    columnInstanceAPI: 'toggleVisibility',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
];
