import { type MRT_Row } from 'material-react-table';

export interface RowInstanceAPI {
  rowInstanceAPI: keyof MRT_Row<RowInstanceAPI>;
  link: string;
  linkText: string;
  description: string;
  type: string;
}

export const rowInstanceAPIs: RowInstanceAPI[] = [
  {
    rowInstanceAPI: 'columnFilters',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'columnFiltersMeta',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'depth',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getAllCells',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCanExpand',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCanMultiSelect',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCanPin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCanSelect',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCanSelectSubRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getCenterVisibleCells',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getGroupingValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsAllParentsExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsAllSubRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsGrouped',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsPinned',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getIsSomeSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getLeafRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getLeftVisibleCells',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getParentRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getParentRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getPinnedIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getRightVisibleCells',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getToggleExpandedHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getToggleSelectedHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getUniqueValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'getVisibleCells',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'id',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'index',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'original',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'originalSubRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'parentId',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'pin',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'renderValue',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'subRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'toggleExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    rowInstanceAPI: 'toggleSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
];
