import { type MRT_TableInstance } from 'material-react-table';

export interface TableInstanceAPI {
  tableInstanceAPI: keyof MRT_TableInstance<TableInstanceAPI>;
  link: string;
  linkText: string;
  description: string;
  type: string;
}

export const tableInstanceAPIs: TableInstanceAPI[] = [
  {
    tableInstanceAPI: 'getAllColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getAllFlatColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getAllLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getBottomRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanNextPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanPreviousPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanSomeRowsExpand',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterFlatHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterFooterGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterHeaderGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterLeafHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterTotalSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterVisibleLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getColumn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCoreRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getExpandedDepth',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getExpandedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFilteredRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFilteredSelectedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFlatHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFooterGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalAutoFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedMinMaxValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedUniqueValues',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGroupedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGroupedSelectedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getHeaderGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllColumnsVisible',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllPageRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllRowsExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeColumnsPinned',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeColumnsVisible',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomePageRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeRowsExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeRowsPinned',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeafHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftFlatHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftFooterGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftHeaderGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftLeafHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftTotalSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftVisibleLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPageCount',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRowCount',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPageOptions',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPaginationRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreExpandedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreFilteredRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreGroupedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPrePaginationRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreSelectedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreSortedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightFlatHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightFooterGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightHeaderGroups',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightLeafHeaders',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightTotalSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightVisibleLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getSelectedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getSortedRowModel',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getState',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllColumnsVisibilityHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllPageRowsSelectedHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllRowsExpandedHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllRowsSelectedHandler',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getTopRows',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getTotalSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getVisibleFlatColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getVisibleLeafColumns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'initialState',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'nextPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'options',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'previousPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'refs',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'reset',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnFilters',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnOrder',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnPinning',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnSizing',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnVisibility',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetGlobalFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetGrouping',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetHeaderSizeInfo',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPageIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPageSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPagination',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetRowPinning',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetRowSelection',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetSorting',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnFilterFns',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnFilters',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnOrder',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnPinning',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnSizing',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnSizingInfo',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnVisibility',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setCreatingRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setDensity',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setDraggingColumn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setDraggingRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setEditingCell',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setEditingRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setGlobalFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setGlobalFilterFn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setGrouping',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setHoveredColumn',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setHoveredRow',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setIsFullScreen',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setOptions',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'lastPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'firstPage',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setPageIndex',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setPageSize',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setPagination',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setRowPinning',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setRowSelection',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowAlertBanner',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowColumnFilters',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowGlobalFilter',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowToolbarDropZone',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setSorting',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setState',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllColumnsVisible',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllPageRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllRowsExpanded',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllRowsSelected',
    type: '',
    description: '',
    link: '',
    linkText: '',
  },
];
