export type User = {
  id: string;
  firstName: string;
  lastName: string;
  city: string;
  state: string;
  managerId: string | null;
  subRows?: User[];
};

export const fakeData: User[] = [
  {
    id: '1',
    firstName: 'Dylan',
    lastName: 'Murray',
    city: 'East Daphne',
    state: 'Kentucky',
    managerId: null,
    subRows: [
      {
        id: '1.1',
        firstName: 'Ervin',
        lastName: 'Reinger',
        city: 'South Linda',
        state: 'West Virginia',
        managerId: '1',
        subRows: [
          {
            id: '1.1.1',
            firstName: 'Jordane',
            lastName: 'Homenick',
            city: 'South Linda',
            state: 'West Virginia',
            managerId: '1.1',
          },
          {
            id: '1.1.2',
            firstName: 'Jordan',
            lastName: 'Clarkson',
            city: 'San Francisco',
            state: 'California',
            managerId: '1.1',
          },
        ],
      },
      {
        id: '1.2',
        firstName: 'Brittany',
        lastName: 'McCullough',
        city: 'Lincoln',
        state: 'Nebraska',
        managerId: '1',
      },
    ],
  },
  {
    id: '2',
    firstName: 'Raquel',
    lastName: 'Kohler',
    city: 'Columbus',
    state: 'Ohio',
    managerId: null,
    subRows: [
      {
        id: '2.1',
        firstName: 'Branson',
        lastName: 'Frami',
        city: 'Charleston',
        state: 'South Carolina',
        managerId: '2',
      },
    ],
  },
  {
    id: '3',
    firstName: 'Jordon',
    lastName: 'Harris',
    city: 'Perth',
    state: 'Western Australia',
    managerId: null,
    subRows: [
      {
        id: '3.1',
        firstName: 'Eldora',
        lastName: 'Koch',
        city: 'Perth',
        state: 'Western Australia',
        managerId: '3',
      },
      {
        id: '3.2',
        firstName: 'Glenn',
        lastName: 'Crist',
        city: 'Darwin',
        state: 'Northern Territory',
        managerId: '3',
      },
    ],
  },
];

//50 us states array
export const usStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
  'Western Australia',
  'Northern Territory',
  'South Australia',
  'Queensland',
];
