name: '🐛 Bug report'
description: Report a reproducible bug or regression
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
        - material-react-table's [Discussions tab](https://github.com/material/material-react-table/discussions)
        - material-react-table's [Open Issues](https://github.com/KevinVandy/material-react-table/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
        - material-react-table's [Closed Issues](https://github.com/KevinVandy/material-react-table/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)

        The more information you fill in, the better the community can help you.

  - type: input
    id: mrt-library-version
    attributes:
      label: material-react-table version
      description: |
        - Please let us know the exact version of material-react-table you were using when the issue occurred. If you are using an older version, check to see if your bug has already been solved in the latest version. 
        - The latest version is <img alt="" src="https://badgen.net/npm/v/material-react-table" />
      placeholder: |
        e.g. v1.3.4
    validations:
      required: true

  - type: input
    id: react-library-version
    attributes:
      label: react & react-dom versions
      description: Material UI v5 requires React and React-Dom v17 or higher
      placeholder: |
        e.g. v17.0.2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug and the steps to reproduce it
      description: Provide a clear and concise description of the challenge you are running into, and the steps we should take to try to reproduce your bug.
    validations:
      required: true

  - type: textarea
    id: link
    attributes:
      label: Minimal, Reproducible Example - (Optional, but Recommended)
      description: |
        Please add a link to a minimal reproduction. This can really speed up the diagnosis of the problem! A Code Sandbox is preferable, but simple code snippets are also acceptable here. Feel free to fork any of the official CodeSandbox examples: https://github.com/KevinVandy/material-react-table/tree/v2/apps/material-react-table-docs/examples
      placeholder: |
        e.g. Code Sandbox, Stackblitz, or relevant code snippets.
    validations:
      required: true

  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos (Optional)
      description: |
        If applicable, add screenshots or a video to help explain your problem.
      placeholder: |
        You can drag your video or image files inside of this editor ↓

  - type: dropdown
    attributes:
      options:
        - No, because I do not know how
        - No, because I do not have time to dig into it
        - Maybe, I'll investigate and start debugging
        - Yes, I think I know how to fix it and will discuss it in the comments of this issue
        - Yes, I am also opening a PR that solves the problem along side this issue
      label: Do you intend to try to help solve this bug with your own PR?
      description: |
        If you think you know the cause of the problem, the fastest way to get it fixed is to suggest a fix, or fix it yourself! However, it is ok if you cannot solve this yourself and are just wanting help.

  - type: checkboxes
    id: agrees-to-terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our Code of Conduct and can verify that you have followed the requirements outlined above to the best of your ability.
      options:
        - label: I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
          required: true
