import { MRT_TableState } from 'material-react-table';

export type StateRow = {
  defaultValue?: string;
  description?: string;
  link?: string;
  linkText?: string;
  source?: 'MRT' | 'TanStack Table' | 'MUI' | '';
  stateName: keyof MRT_TableState;
  type?: string;
};

export const stateOptions: StateRow[] = [
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnFilters',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnOrder',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnPinning',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnSizing',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnSizingInfo',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'columnVisibility',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'currentEditingCell',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'currentEditingRow',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'currentFilterFns',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'currentGlobalFilterFn',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'expanded',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'globalFilter',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'grouping',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'isDensePadding',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'isFullScreen',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'isLoading',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'pagination',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'rowSelection',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'showFilters',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'showGlobalFilter',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'showProgressBars',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'MRT',
    stateName: 'showSkeletons',
    type: '',
  },
  {
    defaultValue: '',
    description: '',
    link: '',
    linkText: '',
    source: 'TanStack Table',
    stateName: 'sorting',
    type: '',
  },
];
