import { MRT_TableInstance } from 'material-react-table';

export interface TableInstanceAPI {
  tableInstanceAPI: keyof MRT_TableInstance;
  link?: string;
  linkText?: string;
  description?: string;
}

export const tableInstanceAPIs: TableInstanceAPI[] = [
  {
    tableInstanceAPI: 'getAllColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getAllFlatColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getAllLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanNextPage',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanPreviousPage',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCanSomeRowsExpand',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterFlatHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterFooterGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterHeaderGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterLeafHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterTotalSize',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getCenterVisibleLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'getColumn', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'getCoreRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getExpandedDepth',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getExpandedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFilteredRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFilteredSelectedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFlatHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getFooterGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalAutoFilterFn',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedMinMaxValues',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFacetedUniqueValues',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGlobalFilterFn',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGroupedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getGroupedSelectedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getHeaderGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllColumnsVisible',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllPageRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllRowsExpanded',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsAllRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeColumnsPinned',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeColumnsVisible',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomePageRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeRowsExpanded',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getIsSomeRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeafHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftFlatHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftFooterGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftHeaderGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftLeafHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftTotalSize',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getLeftVisibleLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'getPageCount', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'getPageOptions',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPaginationRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreExpandedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreFilteredRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreGroupedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPrePaginationRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreSelectedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getPreSortedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightFlatHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightFooterGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightHeaderGroups',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightLeafHeaders',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightTotalSize',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getRightVisibleLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'getRow', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'getRowModel', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'getSelectedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getSortedRowModel',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'getState', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'getToggleAllColumnsVisibilityHandler',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllPageRowsSelectedHandler',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllRowsExpandedHandler',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getToggleAllRowsSelectedHandler',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'getTotalSize', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'getVisibleFlatColumns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'getVisibleLeafColumns',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'initialState', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'nextPage', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'options', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'previousPage', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'refs', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'reset', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'resetColumnFilters',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnOrder',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnPinning',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnSizing',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetColumnVisibility',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetExpanded',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetGlobalFilter',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetGrouping',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetHeaderSizeInfo',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPageIndex',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPageSize',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetPagination',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'resetRowSelection',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'resetSorting', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'setColumnFilterFns',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnFilters',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnOrder',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnPinning',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnSizing',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnSizingInfo',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setColumnVisibility',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'setDensity', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'setDraggingColumn',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setDraggingRow',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setEditingCell',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setEditingRow',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'setExpanded', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'setGlobalFilter',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setGlobalFilterFn',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'setGrouping', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'setHoveredColumn',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setHoveredRow',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setIsFullScreen',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'setOptions', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'setPageCount', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'setPageIndex', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'setPageSize', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'setPagination',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setRowSelection',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowAlertBanner',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowFilters',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'setShowGlobalFilter',
    description: '',
    link: '',
    linkText: '',
  },
  { tableInstanceAPI: 'setSorting', description: '', link: '', linkText: '' },
  { tableInstanceAPI: 'setState', description: '', link: '', linkText: '' },
  {
    tableInstanceAPI: 'toggleAllColumnsVisible',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllPageRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllRowsExpanded',
    description: '',
    link: '',
    linkText: '',
  },
  {
    tableInstanceAPI: 'toggleAllRowsSelected',
    description: '',
    link: '',
    linkText: '',
  },
];
