export type Person = {
  firstName: string;
  lastName: string;
  address: string;
  city: string;
  state: string;
};

export const data: Person[] = [
  {
    firstName: 'Alberta',
    lastName: 'Kautzer',
    address: '82321 Reichert Bridge',
    city: 'Armandoland',
    state: 'Mississippi',
  },
  {
    firstName: 'Imelda',
    lastName: 'Harber',
    address: '866 Kuvalis Groves',
    city: 'North Kieran',
    state: 'Iowa',
  },
  {
    firstName: 'Leonie',
    lastName: 'Hickle',
    address: '6094 Hudson Park',
    city: 'Mandytown',
    state: 'Oregon',
  },
  {
    firstName: 'Cristal',
    lastName: 'Carroll',
    address: '41222 Webster Oval',
    city: 'South Blaze',
    state: 'New Mexico',
  },
  {
    firstName: 'Golda',
    lastName: 'Brakus',
    address: '13718 Blick Port',
    city: 'Fort Tressachester',
    state: 'New Mexico',
  },
  {
    firstName: 'Jackeline',
    lastName: 'Little',
    address: '130 Kuhlman Creek',
    city: 'Gordonworth',
    state: 'Ohio',
  },
  {
    firstName: 'Karson',
    lastName: 'Flatley',
    address: '9494 McCullough Stravenue',
    city: 'Pricemouth',
    state: 'Delaware',
  },
  {
    firstName: 'Jonathan',
    lastName: 'Bednar',
    address: '79954 Klein Loaf',
    city: 'Abdielville',
    state: 'Indiana',
  },
  {
    firstName: 'Rocky',
    lastName: 'Funk',
    address: '602 Josianne Ramp',
    city: 'Fort Pearlworth',
    state: 'Mississippi',
  },
  {
    firstName: 'Anthony',
    lastName: 'Stokes',
    address: '71571 Santa Mission',
    city: 'Beaumont',
    state: 'Alaska',
  },
  {
    firstName: 'Brenden',
    lastName: 'Gislason',
    address: '1291 Lyla Gateway',
    city: 'Lacey',
    state: 'North Carolina',
  },
  {
    firstName: 'Webster',
    lastName: 'Ankunding',
    address: '229 Yasmin Passage',
    city: 'Doylefurt',
    state: 'Arizona',
  },
  {
    firstName: 'Marley',
    lastName: 'Towne',
    address: '5895 Bartoletti Falls',
    city: 'Kendale Lakes',
    state: 'Indiana',
  },
  {
    firstName: 'Alexandrine',
    lastName: 'Hintz',
    address: '89462 Halvorson Junction',
    city: 'Jerrodview',
    state: 'Missouri',
  },
  {
    firstName: 'Xavier',
    lastName: 'Lowe',
    address: '829 Rodriguez Mall',
    city: 'Grantberg',
    state: 'Texas',
  },
  {
    firstName: 'Camden',
    lastName: 'Kemmer',
    address: '3110 Andreane Villages',
    city: 'Corpus Christi',
    state: 'Nebraska',
  },
  {
    firstName: 'Ashtyn',
    lastName: 'Hermiston',
    address: '6087 Howell Ports',
    city: 'Castro Valley',
    state: 'Tennessee',
  },
  {
    firstName: 'Kaylee',
    lastName: 'Baumbach',
    address: '9576 Kristina Stravenue',
    city: 'South Beverly',
    state: 'Colorado',
  },
  {
    firstName: 'Eugene',
    lastName: 'VonRueden',
    address: '43151 Rogelio Alley',
    city: 'Balistrerifurt',
    state: 'Tennessee',
  },
  {
    firstName: 'Robin',
    lastName: 'McDermott',
    address: '5032 Batz Valleys',
    city: 'Shaynabury',
    state: 'Montana',
  },
  {
    firstName: 'Hilbert',
    lastName: 'Marks',
    address: '25426 Verda Extension',
    city: "O'Reillyville",
    state: 'North Dakota',
  },
  {
    firstName: 'Allan',
    lastName: 'Schulist',
    address: '6789 Predovic Skyway',
    city: 'Skilesport',
    state: 'Maryland',
  },
  {
    firstName: 'Julian',
    lastName: 'Friesen',
    address: '54634 Bogisich Brooks',
    city: 'West Carterbury',
    state: 'Illinois',
  },
  {
    firstName: 'Kathryne',
    lastName: 'Schoen',
    address: '106 Berge Lakes',
    city: 'West Boyd',
    state: 'Kansas',
  },
  {
    firstName: 'Franco',
    lastName: 'Langworth',
    address: '5475 Cummings Forks',
    city: 'Simonisborough',
    state: 'West Virginia',
  },
  {
    firstName: 'Devyn',
    lastName: 'Lehner',
    address: '33190 Delphia Stravenue',
    city: 'Rowland Heights',
    state: 'New Jersey',
  },
  {
    firstName: 'Morton',
    lastName: 'Kerluke',
    address: '678 Ernestina Fords',
    city: 'Milwaukee',
    state: 'North Carolina',
  },
  {
    firstName: 'Tate',
    lastName: 'Goldner',
    address: '17975 Ledner Falls',
    city: 'Arvada',
    state: 'Wyoming',
  },
  {
    firstName: 'Earlene',
    lastName: 'Considine',
    address: '4418 Fritsch Shores',
    city: 'South Morgan',
    state: 'Oklahoma',
  },
  {
    firstName: 'Oran',
    lastName: 'Hayes',
    address: '239 Bergnaum Trail',
    city: 'East Vaughn',
    state: 'Connecticut',
  },
  {
    firstName: 'Ashly',
    lastName: 'Legros',
    address: '8556 Bernard Corners',
    city: 'Spencerborough',
    state: 'Alaska',
  },
  {
    firstName: 'Dolores',
    lastName: 'Hilll',
    address: '454 Laurie Valley',
    city: 'South Emilio',
    state: 'Washington',
  },
  {
    firstName: 'Luella',
    lastName: 'Bailey',
    address: '935 Weissnat Flats',
    city: "O'Haraberg",
    state: 'Oklahoma',
  },
  {
    firstName: 'Wallace',
    lastName: 'Fahey',
    address: '6144 Bailey Row',
    city: 'Runolfssonstead',
    state: 'Oregon',
  },
  {
    firstName: 'Taylor',
    lastName: 'Simonis',
    address: '326 Dena Stravenue',
    city: 'Lakewood',
    state: 'Wyoming',
  },
  {
    firstName: 'Nicolette',
    lastName: 'Fisher',
    address: '20337 Diego Orchard',
    city: 'Claudemouth',
    state: 'Maine',
  },
  {
    firstName: 'Vesta',
    lastName: 'Mohr',
    address: '83938 Harvey Freeway',
    city: 'North Jasonworth',
    state: 'Iowa',
  },
  {
    firstName: 'Tracy',
    lastName: 'Frami',
    address: '9951 Baylee Station',
    city: 'Casperworth',
    state: 'Illinois',
  },
  {
    firstName: 'Isaias',
    lastName: 'Larkin',
    address: '670 Valentine Burgs',
    city: 'San Leandro',
    state: 'Pennsylvania',
  },
  {
    firstName: 'Melyna',
    lastName: 'Parker',
    address: '363 Antonina Shoals',
    city: 'West Curtisboro',
    state: 'Mississippi',
  },
  {
    firstName: 'Mae',
    lastName: 'Robel',
    address: '243 Friesen Ports',
    city: 'Arvidstead',
    state: 'Nebraska',
  },
  {
    firstName: 'Gino',
    lastName: 'Zieme',
    address: '929 Carmel Cliffs',
    city: 'Minnetonka',
    state: 'South Dakota',
  },
  {
    firstName: 'Lacy',
    lastName: 'Hirthe',
    address: '36196 Madyson Common',
    city: 'Lancaster',
    state: 'Pennsylvania',
  },
  {
    firstName: 'Brady',
    lastName: 'Fritsch',
    address: '5798 Kub Park',
    city: 'Lake Dannie',
    state: 'North Dakota',
  },
  {
    firstName: 'Efrain',
    lastName: 'Swift',
    address: '527 Conroy Course',
    city: 'Boydport',
    state: 'Wyoming',
  },
  {
    firstName: 'Kathlyn',
    lastName: 'Hayes',
    address: '9788 Sylvia Orchard',
    city: 'Medford',
    state: 'Michigan',
  },
  {
    firstName: 'Dion',
    lastName: 'Stracke',
    address: '04091 Elda Trail',
    city: 'Gerardmouth',
    state: 'Kentucky',
  },
  {
    firstName: 'Carlotta',
    lastName: 'Satterfield',
    address: '68542 Tina Road',
    city: 'Meridian',
    state: 'Rhode Island',
  },
  {
    firstName: 'Estrella',
    lastName: 'Will',
    address: '16208 Hermiston Walk',
    city: 'North Havenland',
    state: 'Georgia',
  },
  {
    firstName: 'Alena',
    lastName: 'Blick',
    address: '980 Heaney Flat',
    city: 'Lake Vallie',
    state: 'Hawaii',
  },
  {
    firstName: 'Marco',
    lastName: 'Bins',
    address: '166 McClure Locks',
    city: 'Richardson',
    state: 'Maryland',
  },
  {
    firstName: 'Damon',
    lastName: 'Bernier',
    address: '66146 Dulce Islands',
    city: "O'Connerfort",
    state: 'Alaska',
  },
  {
    firstName: 'Rosina',
    lastName: 'Green',
    address: '795 Thiel Fords',
    city: 'Steuberbury',
    state: 'Kansas',
  },
  {
    firstName: 'Alejandra',
    lastName: 'Hudson',
    address: '14994 Hudson Locks',
    city: 'Kasandraside',
    state: 'Minnesota',
  },
  {
    firstName: 'Bradly',
    lastName: 'Green',
    address: '3828 Beatty Turnpike',
    city: 'Glen Burnie',
    state: 'Rhode Island',
  },
  {
    firstName: 'Madeline',
    lastName: 'Rempel',
    address: '22922 Zulauf Park',
    city: 'South Katlynnboro',
    state: 'Missouri',
  },
  {
    firstName: 'Oceane',
    lastName: 'Rolfson',
    address: '64053 Ava Ridge',
    city: 'Sammouth',
    state: 'Mississippi',
  },
  {
    firstName: 'Raymundo',
    lastName: 'Koepp',
    address: '13389 Langworth Street',
    city: 'Mosciskihaven',
    state: 'Alabama',
  },
  {
    firstName: 'Jamey',
    lastName: 'Stiedemann',
    address: '2435 Nick Well',
    city: 'Langville',
    state: 'Kansas',
  },
  {
    firstName: 'Isabel',
    lastName: 'Johnston',
    address: '4188 Florida Curve',
    city: 'Blacksburg',
    state: 'Texas',
  },
  {
    firstName: 'Lelia',
    lastName: 'Torphy',
    address: '8221 Louie Divide',
    city: 'Port Eda',
    state: 'Vermont',
  },
  {
    firstName: 'Angelica',
    lastName: 'Huels',
    address: '60339 Altenwerth Island',
    city: 'New Betsy',
    state: 'Louisiana',
  },
  {
    firstName: 'Virginia',
    lastName: 'Stamm',
    address: '78943 Skiles Bridge',
    city: 'Natmouth',
    state: 'Wyoming',
  },
  {
    firstName: 'Jacquelyn',
    lastName: 'Medhurst',
    address: '61369 Schiller Stravenue',
    city: 'Morissettefort',
    state: 'New Jersey',
  },
  {
    firstName: 'Kassandra',
    lastName: 'Ullrich',
    address: '7495 Sandrine Stravenue',
    city: 'South Dennisfurt',
    state: 'Arizona',
  },
  {
    firstName: 'Nicklaus',
    lastName: 'Zulauf',
    address: '8925 Jacky View',
    city: 'Fort Angelineburgh',
    state: 'South Carolina',
  },
  {
    firstName: 'Herman',
    lastName: 'Toy',
    address: '2281 Runolfsson Junctions',
    city: 'North Koleshire',
    state: 'Michigan',
  },
  {
    firstName: 'Leda',
    lastName: 'Doyle',
    address: '08671 Smitham Rapids',
    city: 'Lake Ona',
    state: 'Missouri',
  },
  {
    firstName: 'Salvatore',
    lastName: 'Haley',
    address: '07365 Nicolas Valley',
    city: 'West Darien',
    state: 'California',
  },
  {
    firstName: 'Rod',
    lastName: 'Durgan',
    address: '4363 Candace Lake',
    city: 'Dariotown',
    state: 'Utah',
  },
  {
    firstName: 'Ali',
    lastName: 'Schroeder',
    address: '366 Raymundo Ports',
    city: 'Lake Quinn',
    state: 'Indiana',
  },
  {
    firstName: 'Noelia',
    lastName: 'Bayer',
    address: '04284 Windler Hill',
    city: 'New Daron',
    state: 'Hawaii',
  },
  {
    firstName: 'Rhianna',
    lastName: 'Von',
    address: '7240 Dariana Estates',
    city: 'Fort Coralietown',
    state: 'Arkansas',
  },
  {
    firstName: 'Santiago',
    lastName: 'Jaskolski',
    address: '2735 Jeanie Bypass',
    city: 'Athens-Clarke County',
    state: 'West Virginia',
  },
  {
    firstName: 'Nestor',
    lastName: 'Parisian',
    address: '803 Marty Ramp',
    city: 'Funkside',
    state: 'North Carolina',
  },
  {
    firstName: 'Laila',
    lastName: 'Mann',
    address: '43016 Beier Plaza',
    city: 'Port Hilmamouth',
    state: 'Oklahoma',
  },
  {
    firstName: 'Boyd',
    lastName: 'Bahringer',
    address: '62900 Von Heights',
    city: 'North Art',
    state: 'Michigan',
  },
  {
    firstName: 'Craig',
    lastName: 'Jacobs',
    address: '70148 Tod Cape',
    city: 'Mayerworth',
    state: 'West Virginia',
  },
  {
    firstName: 'Cecil',
    lastName: 'Zboncak',
    address: '025 Lenna Mountain',
    city: 'Centreville',
    state: 'Hawaii',
  },
  {
    firstName: 'Verner',
    lastName: 'Lockman',
    address: '034 Runte Oval',
    city: 'South Ernie',
    state: 'North Carolina',
  },
  {
    firstName: 'Emmett',
    lastName: "D'Amore",
    address: '78625 Morton Walks',
    city: 'New Eliezerborough',
    state: 'South Carolina',
  },
  {
    firstName: "D'angelo",
    lastName: 'Jacobson',
    address: '577 Khalid Ridges',
    city: 'Kilbackstad',
    state: 'Florida',
  },
  {
    firstName: 'Oceane',
    lastName: 'Kassulke',
    address: '24350 Joana Circles',
    city: 'Greenview',
    state: 'Connecticut',
  },
  {
    firstName: 'Eudora',
    lastName: 'Dibbert',
    address: '905 Gordon Mills',
    city: 'New Willieside',
    state: 'Washington',
  },
  {
    firstName: 'Sheridan',
    lastName: 'Kling',
    address: '9108 Armstrong Lights',
    city: 'Hoegerchester',
    state: 'Illinois',
  },
  {
    firstName: 'Hailie',
    lastName: 'Fadel',
    address: '3000 Hagenes Turnpike',
    city: 'Forrestborough',
    state: 'Nebraska',
  },
];
