export type Person = {
  firstName: string;
  lastName: string;
  email: string;
  address: string;
  city: string;
  state: string;
  country: string;
};

export const data: Person[] = [
  {
    firstName: 'Mason',
    lastName: 'Anderson',
    email: 'manderson57@yopmail.com',
    address: '1234 Main St',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
  },
  {
    firstName: 'Nora',
    lastName: 'Bishop',
    email: 'nbishop26@mailinator.com',
    address: '1234 Main St',
    city: 'Portland',
    state: 'OR',
    country: 'USA',
  },
  {
    firstName: 'Liam',
    lastName: 'Patterson',
    email: 'lpatterson61@yopmail.com',
    address: '1234 Main St',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
  },
  {
    firstName: 'Harper',
    lastName: 'Ross',
    email: 'hross38@mailinator.com',
    address: '1234 Main St',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
  },
  {
    firstName: 'Oliver',
    lastName: 'Baker',
    email: 'obaker72@yopmail.com',
    address: '1234 Main St',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Phillips',
    email: 'cphillips33@mailinator.com',
    address: '1234 Main St',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
  },
  {
    firstName: 'Henry',
    lastName: 'Cooper',
    email: 'hcooper18@yopmail.com',
    address: '1234 Main St',
    city: 'Denver',
    state: 'CO',
    country: 'USA',
  },
  {
    firstName: 'Emma',
    lastName: 'Jenkins',
    email: 'ejenkins49@mailinator.com',
    address: '1234 Main St',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
  },
  {
    firstName: 'Alexander',
    lastName: 'Gonzalez',
    email: 'agonzalez67@yopmail.com',
    address: '1234 Main St',
    city: 'Dallas',
    state: 'TX',
    country: 'USA',
  },
  {
    firstName: 'Ava',
    lastName: 'Ramirez',
    email: 'aramirez94@mailinator.com',
    address: '1234 Main St',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
  },
  {
    firstName: 'William',
    lastName: 'Bailey',
    email: 'wbailey59@yopmail.com',
    address: '1234 Main St',
    city: 'Phoenix',
    state: 'AZ',
    country: 'USA',
  },
  {
    firstName: 'Sophia',
    lastName: 'Cox',
    email: 'scox77@mailinator.com',
    address: '1234 Main St',
    city: 'Atlanta',
    state: 'GA',
    country: 'USA',
  },
  {
    firstName: 'James',
    lastName: 'Sanders',
    email: 'jsanders26@yopmail.com',
    address: '1234 Main St',
    city: 'Detroit',
    state: 'MI',
    country: 'USA',
  },
  {
    firstName: 'Mia',
    lastName: 'Long',
    email: 'mlong33@mailinator.com',
    address: '1234 Main St',
    city: 'Philadelphia',
    state: 'PA',
    country: 'USA',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Bennett',
    email: 'bbennett92@yopmail.com',
    address: '1234 Main St',
    city: 'Washington, D.C.',
    state: 'DC',
    country: 'USA',
  },
  {
    firstName: 'Dylan',
    lastName: 'Murray',
    email: 'dmurray@yopmail.com',
    address: '1234 Main St',
    city: 'East Daphne',
    state: 'AL',
    country: 'USA',
  },
  {
    firstName: 'Raquel',
    lastName: 'Kohler',
    email: 'rkholer33@yopmail.com',
    address: '1234 Main St',
    city: 'Columbus',
    state: 'OH',
    country: 'USA',
  },
  {
    firstName: 'Ervin',
    lastName: 'Reinger',
    email: 'ereinger@mailinator.com',
    address: '1234 Main St',
    city: 'South Linda',
    state: 'CA',
    country: 'USA',
  },
  {
    firstName: 'Brittany',
    lastName: 'McCullough',
    email: 'bmccullough44@mailinator.com',
    address: '1234 Main St',
    city: 'Lincoln',
    state: 'NE',
    country: 'USA',
  },
  {
    firstName: 'Branson',
    lastName: 'Frami',
    email: 'bframi@yopmain.com',
    address: '1234 Main St',
    city: 'New York',
    state: 'NY',
    country: 'USA',
  },
  {
    firstName: 'Julia',
    lastName: 'Thomas',
    email: 'jthomas42@mailinator.com',
    address: '1234 Main St',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
  },
];
