export type Person = {
  firstName: string;
  lastName: string;
  address: string;
  city: string;
  state: string;
};

export const data: Person[] = [
  {
    firstName: 'Kyleigh',
    lastName: 'Padberg',
    address: '57128 Layla Canyon',
    city: 'Sedrickfurt',
    state: 'Alabama',
  },
  {
    firstName: 'Madelynn',
    lastName: 'Conroy',
    address: '006 Edna Well',
    city: 'Oak Lawn',
    state: 'Utah',
  },
  {
    firstName: 'Lisette',
    lastName: 'King',
    address: '37090 Jordon Light',
    city: 'Fort Natalie',
    state: 'Oregon',
  },
  {
    firstName: 'Emmet',
    lastName: 'Medhurst',
    address: '27667 Tillman Drive',
    city: 'Pittsburg',
    state: 'Vermont',
  },
  {
    firstName: 'Melissa',
    lastName: 'Stark',
    address: '70121 Gleichner Expressway',
    city: 'East Cary',
    state: 'Florida',
  },
  {
    firstName: 'Thaddeus',
    lastName: 'Davis',
    address: '250 Maybell Springs',
    city: 'East Norvalmouth',
    state: 'Missouri',
  },
  {
    firstName: 'Nettie',
    lastName: 'Flatley',
    address: '96048 Abernathy Way',
    city: 'South Jackie',
    state: 'Maine',
  },
  {
    firstName: 'Narciso',
    lastName: 'Veum',
    address: '164 Prosacco Estate',
    city: 'Lake Linwoodstead',
    state: 'Florida',
  },
  {
    firstName: 'Giovani',
    lastName: 'Wolff',
    address: '66888 Cullen Center',
    city: 'New Nicolashaven',
    state: 'Rhode Island',
  },
  {
    firstName: 'Jalen',
    lastName: 'Cormier',
    address: '50679 Darby Drive',
    city: 'Jamaalburgh',
    state: 'Texas',
  },
  {
    firstName: 'Jasmin',
    lastName: 'Gibson',
    address: '72724 Crist Groves',
    city: 'West Harley',
    state: 'Illinois',
  },
  {
    firstName: 'Mohammad',
    lastName: 'Hamill',
    address: '443 Wilhelm Plaza',
    city: 'Terre Haute',
    state: 'New Mexico',
  },
  {
    firstName: 'Milo',
    lastName: 'Dicki',
    address: '778 Wilfred Meadow',
    city: 'Krisland',
    state: 'Arkansas',
  },
  {
    firstName: 'Erich',
    lastName: 'Lynch',
    address: '60472 Price Parks',
    city: 'Lake Mavis',
    state: 'Illinois',
  },
  {
    firstName: 'Deontae',
    lastName: 'Boyle',
    address: '4573 Zboncak Underpass',
    city: 'Dandrefort',
    state: 'Michigan',
  },
  {
    firstName: 'Antwon',
    lastName: 'Turcotte',
    address: '80006 Luettgen Well',
    city: 'New Lucienneshire',
    state: 'West Virginia',
  },
  {
    firstName: 'Marcella',
    lastName: 'Hermann',
    address: '0339 Kunde Junctions',
    city: 'Tallahassee',
    state: 'Alaska',
  },
  {
    firstName: 'Maud',
    lastName: 'Abernathy',
    address: '3590 Shayna Path',
    city: 'North Afton',
    state: 'South Carolina',
  },
  {
    firstName: 'Asa',
    lastName: 'Crist',
    address: '675 Tamara Corner',
    city: 'North Melody',
    state: 'New Mexico',
  },
  {
    firstName: 'Anita',
    lastName: 'Wiza',
    address: '47680 Rhianna Roads',
    city: 'Welchhaven',
    state: 'Ohio',
  },
  {
    firstName: 'Glennie',
    lastName: 'Runolfsdottir',
    address: '2198 Casimer Meadows',
    city: 'Creminchester',
    state: 'Illinois',
  },
  {
    firstName: 'Ashlynn',
    lastName: 'Rau',
    address: '12277 Johnson Passage',
    city: 'Lake Hayleemouth',
    state: 'Idaho',
  },
  {
    firstName: 'Kylee',
    lastName: 'Douglas',
    address: '52782 Arvilla Manors',
    city: 'Mayaguez',
    state: 'Nebraska',
  },
  {
    firstName: 'Matt',
    lastName: 'Muller',
    address: '9615 Baumbach Heights',
    city: 'Madelynburgh',
    state: 'Michigan',
  },
  {
    firstName: 'Ralph',
    lastName: 'Kulas',
    address: '7102 Parker Gateway',
    city: 'East Polly',
    state: 'Arkansas',
  },
  {
    firstName: 'Joey',
    lastName: 'Altenwerth',
    address: '3670 Maverick Valley',
    city: 'West Seamus',
    state: 'Arizona',
  },
  {
    firstName: 'Tito',
    lastName: 'Thompson',
    address: '6870 Maribel Rapids',
    city: 'North Michelle',
    state: 'Vermont',
  },
  {
    firstName: 'Makenzie',
    lastName: 'Lindgren',
    address: '67829 Salvatore Extension',
    city: 'Auburn',
    state: 'Louisiana',
  },
  {
    firstName: 'Isabelle',
    lastName: 'Schaefer',
    address: '46296 Susan Tunnel',
    city: 'South Kellymouth',
    state: 'Maryland',
  },
  {
    firstName: 'Mandy',
    lastName: 'Spencer',
    address: '9131 Amie Spurs',
    city: 'New Laurianeberg',
    state: 'Connecticut',
  },
  {
    firstName: 'Marianne',
    lastName: 'Legros',
    address: '61718 Steuber Ways',
    city: 'Yundtstead',
    state: 'Florida',
  },
  {
    firstName: 'Gordon',
    lastName: 'Herzog',
    address: '2177 Beer Harbor',
    city: 'Beckerberg',
    state: 'Maryland',
  },
  {
    firstName: 'Richmond',
    lastName: 'White',
    address: '3959 Otto Prairie',
    city: 'Colton',
    state: 'Nebraska',
  },
  {
    firstName: 'Macey',
    lastName: 'Rodriguez',
    address: '55553 Rosemarie Park',
    city: 'Leopoldoberg',
    state: 'Missouri',
  },
  {
    firstName: 'Marcelo',
    lastName: "D'Amore",
    address: '83119 Dakota Mountain',
    city: 'East Quinnfurt',
    state: 'New York',
  },
  {
    firstName: 'Shad',
    lastName: 'Kuvalis',
    address: '5938 Jakubowski Run',
    city: 'Port Yasmeenburgh',
    state: 'Vermont',
  },
  {
    firstName: 'Freddy',
    lastName: 'Ryan',
    address: '779 Weston Mills',
    city: 'Port Gregorioboro',
    state: 'Mississippi',
  },
  {
    firstName: 'Lorenzo',
    lastName: 'Hirthe',
    address: '86093 Ruby Pike',
    city: 'East Wilfredoboro',
    state: 'Maine',
  },
  {
    firstName: 'Hallie',
    lastName: 'Metz',
    address: '1105 Anderson Trafficway',
    city: 'Keaganside',
    state: 'Oregon',
  },
  {
    firstName: 'Arch',
    lastName: 'Bernier',
    address: '56243 Susana Tunnel',
    city: 'East Marilou',
    state: 'Georgia',
  },
  {
    firstName: 'Agnes',
    lastName: 'Gislason',
    address: '09651 Mariah Spur',
    city: 'Lake Audreanne',
    state: 'South Carolina',
  },
  {
    firstName: 'Mekhi',
    lastName: 'Howell',
    address: '9161 Asa Rest',
    city: 'Reichertfurt',
    state: 'South Carolina',
  },
  {
    firstName: 'Jenifer',
    lastName: 'Tromp',
    address: '848 Bobbie Green',
    city: 'Erdmanfort',
    state: 'Idaho',
  },
  {
    firstName: 'Spencer',
    lastName: 'Mertz',
    address: '301 Alex Causeway',
    city: 'Abernathyberg',
    state: 'Colorado',
  },
  {
    firstName: 'Brannon',
    lastName: 'Goldner',
    address: '5149 Keenan Corners',
    city: 'South Zachery',
    state: 'Montana',
  },
  {
    firstName: 'Alexzander',
    lastName: 'DuBuque',
    address: '89077 Goldner Stream',
    city: 'West New York',
    state: 'Arkansas',
  },
  {
    firstName: 'Aylin',
    lastName: 'Runte',
    address: '326 Casper Mountains',
    city: 'Middletown',
    state: 'Oregon',
  },
  {
    firstName: 'Asia',
    lastName: 'Stracke',
    address: '8421 Mueller Junction',
    city: 'Keeleyton',
    state: 'Maine',
  },
  {
    firstName: 'Thomas',
    lastName: 'Harber',
    address: '2409 David Plaza',
    city: 'Fort Mariam',
    state: 'Kansas',
  },
  {
    firstName: 'Elbert',
    lastName: 'Kris',
    address: '04030 Rippin Estate',
    city: 'South Bend',
    state: 'Montana',
  },
  {
    firstName: 'Adell',
    lastName: 'Feest',
    address: '58844 Emmie Roads',
    city: 'Fort Marcellusbury',
    state: 'Illinois',
  },
  {
    firstName: 'Edd',
    lastName: 'Davis',
    address: '1877 Christop Passage',
    city: 'Rowehaven',
    state: 'Texas',
  },
  {
    firstName: 'Jadyn',
    lastName: 'Crist',
    address: '250 Sage Ports',
    city: 'New Lera',
    state: 'Texas',
  },
  {
    firstName: 'Alfred',
    lastName: 'Johnson',
    address: '67767 Will Shore',
    city: 'Olympia',
    state: 'Colorado',
  },
  {
    firstName: 'Demarcus',
    lastName: 'Konopelski',
    address: '6474 Hans Harbor',
    city: 'Trantowworth',
    state: 'New Mexico',
  },
  {
    firstName: 'Kaitlin',
    lastName: 'Littel',
    address: '940 Leffler Mountain',
    city: 'Abnerworth',
    state: 'Texas',
  },
  {
    firstName: 'Franco',
    lastName: 'Yundt',
    address: '1391 Howell Garden',
    city: 'Kenyaboro',
    state: 'Vermont',
  },
  {
    firstName: 'Cara',
    lastName: 'Weissnat',
    address: '97784 Hester Dam',
    city: 'Gislasonfort',
    state: 'New York',
  },
  {
    firstName: 'Hosea',
    lastName: 'Osinski',
    address: '5090 Nicole Wall',
    city: 'Pawtucket',
    state: 'Maryland',
  },
  {
    firstName: 'Casimir',
    lastName: 'Mayert',
    address: '229 Halvorson Groves',
    city: 'Fort Audietown',
    state: 'Rhode Island',
  },
  {
    firstName: 'Clotilde',
    lastName: 'Wiegand',
    address: '7847 Hobart Camp',
    city: 'Port Charlotteburgh',
    state: 'Mississippi',
  },
  {
    firstName: 'Lottie',
    lastName: 'Hermann',
    address: '8898 Verda Knoll',
    city: 'Stratford',
    state: 'Kansas',
  },
  {
    firstName: 'Jayda',
    lastName: 'Wunsch',
    address: '71760 Mina Mission',
    city: 'Jurupa Valley',
    state: 'Rhode Island',
  },
  {
    firstName: 'Rubye',
    lastName: 'Schroeder',
    address: '93479 Phoebe View',
    city: 'Port Glennafurt',
    state: 'New Jersey',
  },
  {
    firstName: 'Marlin',
    lastName: 'Dickens',
    address: '9322 Paucek Summit',
    city: 'Fort Avachester',
    state: 'South Dakota',
  },
  {
    firstName: 'Dean',
    lastName: 'Sauer',
    address: '4096 Carroll Parks',
    city: 'West Helen',
    state: 'Oregon',
  },
  {
    firstName: 'Nickolas',
    lastName: 'Treutel',
    address: '80685 Yundt Radial',
    city: 'Bartonbury',
    state: 'Wyoming',
  },
  {
    firstName: 'Rosendo',
    lastName: 'Yost',
    address: '383 Annamae Lodge',
    city: 'Willport',
    state: 'New Jersey',
  },
  {
    firstName: 'Marlen',
    lastName: 'Wuckert',
    address: '0655 Quitzon Via',
    city: 'Sethfort',
    state: 'Alabama',
  },
  {
    firstName: 'Uriel',
    lastName: 'Anderson',
    address: '882 Oberbrunner Dale',
    city: 'Goyetteborough',
    state: 'South Dakota',
  },
  {
    firstName: 'Uriah',
    lastName: 'Kuvalis',
    address: '811 Weissnat Street',
    city: 'Baton Rouge',
    state: 'Tennessee',
  },
  {
    firstName: 'Clyde',
    lastName: 'Bergstrom',
    address: '656 Trisha Junction',
    city: 'Vitachester',
    state: 'Minnesota',
  },
  {
    firstName: 'Adriana',
    lastName: 'Towne',
    address: '94037 Diana Radial',
    city: 'Zacheryfort',
    state: 'Washington',
  },
  {
    firstName: 'Carole',
    lastName: 'Stamm',
    address: '1701 Leuschke Unions',
    city: 'Walkerburgh',
    state: 'Texas',
  },
  {
    firstName: 'Matilda',
    lastName: 'Mayert',
    address: '7525 Mossie Inlet',
    city: 'Escondido',
    state: 'Minnesota',
  },
  {
    firstName: 'Pattie',
    lastName: 'Gleichner',
    address: '40802 McClure Manor',
    city: 'New Royfort',
    state: 'Nebraska',
  },
  {
    firstName: 'Marcelle',
    lastName: 'Leannon',
    address: '764 Alena Neck',
    city: 'Kiannaside',
    state: 'Hawaii',
  },
  {
    firstName: 'Selmer',
    lastName: 'Dach',
    address: '63058 Daniel Lock',
    city: 'Hamillmouth',
    state: 'Florida',
  },
  {
    firstName: 'Coralie',
    lastName: 'Stokes',
    address: '1467 Millie Fall',
    city: 'Kunzecester',
    state: 'Nebraska',
  },
  {
    firstName: 'Eleanora',
    lastName: 'Macejkovic',
    address: '88046 Mayer Spur',
    city: 'Fort Brianborough',
    state: 'Alabama',
  },
  {
    firstName: 'Camron',
    lastName: 'Walter',
    address: '105 Margot Spring',
    city: 'Cheektowaga',
    state: 'Vermont',
  },
  {
    firstName: 'Dolores',
    lastName: 'Schuppe',
    address: '645 Walker Mountain',
    city: 'Port Rosalyn',
    state: 'Michigan',
  },
  {
    firstName: 'Renee',
    lastName: 'Nicolas',
    address: '6781 Tyra Loop',
    city: 'Hilo',
    state: 'Arizona',
  },
  {
    firstName: 'Rebecca',
    lastName: 'Durgan',
    address: '014 Crist Island',
    city: 'Lake Madisyn',
    state: 'Rhode Island',
  },
  {
    firstName: 'Claudia',
    lastName: 'Tillman',
    address: '62444 Bartoletti Roads',
    city: 'North Liamstad',
    state: 'Nevada',
  },
  {
    firstName: 'Kennedi',
    lastName: 'Jaskolski',
    address: '4418 Koepp Turnpike',
    city: 'West Terrell',
    state: 'Vermont',
  },
  {
    firstName: 'Leon',
    lastName: 'Konopelski',
    address: '651 Mary Plains',
    city: 'San Jose',
    state: 'Illinois',
  },
  {
    firstName: 'Grady',
    lastName: 'Murray',
    address: '480 Kellen Stravenue',
    city: 'East Westley',
    state: 'Oregon',
  },
];
