import { type NextApiRequest, type NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  if (process.env.NODE_ENV === 'development') {
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  const { phoneNumber } = req.query;
  const data = fullData.find(
    (item) =>
      item.phoneNumber
        .replaceAll('-', '')
        .replaceAll('.', '')
        .replaceAll('(', '')
        .replaceAll(')', '') === phoneNumber,
  );
  res.status(200).json(data);
}

const fullData = [
  {
    firstName: 'Hermann',
    lastName: 'Gusikowski',
    address: '6099 Douglas Creek',
    state: 'Georgia',
    phoneNumber: '421.698.9405',
    lastLogin: '2023-08-16T03:21:08.244Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Tom Dooley',
    quote:
      'If we transmit the application, we can get to the PNG driver through the auxiliary SMS port!',
  },
  {
    firstName: 'Milford',
    lastName: 'Torp',
    address: '410 Vicenta Radial',
    state: 'Alabama',
    phoneNumber: '805-728-7771 x75361',
    lastLogin: '2023-05-15T02:45:50.684Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Another Brick in the Wall (part 2)',
    quote:
      'The AGP hard drive is down, generate the online port so we can generate the TCP program!',
  },
  {
    firstName: 'Alda',
    lastName: 'Koss',
    address: '1604 Bernardo Flats',
    state: 'Louisiana',
    phoneNumber: '860.628.3618',
    lastLogin: '2022-02-26T03:23:25.877Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Doo Wop (That Thing)',
    quote:
      "overriding the bandwidth won't do anything, we need to input the back-end JBOD system!",
  },
  {
    firstName: 'Eulah',
    lastName: 'Lockman',
    address: "7072 D'Amore Shoal",
    state: 'Tennessee',
    phoneNumber: '1-394-293-7730 x512',
    lastLogin: '2019-03-31T17:53:49.187Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Over There',
    quote:
      'Use the bluetooth SQL sensor, then you can program the mobile interface!',
  },
  {
    firstName: 'Justen',
    lastName: 'Hilpert',
    address: '386 Murray Walks',
    state: 'North Carolina',
    phoneNumber: '507.430.8224 x561',
    lastLogin: '2023-10-02T19:50:58.197Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Maniac',
    quote:
      'Use the auxiliary PNG matrix, then you can calculate the neural transmitter!',
  },
  {
    firstName: 'Vergie',
    lastName: 'Beatty',
    address: '6864 Mann Haven',
    state: 'Maryland',
    phoneNumber: '1-538-794-7917',
    lastLogin: '2023-06-14T00:27:49.332Z',
    favoriteMusic: 'Country',
    favoriteSong: 'You Sexy Thing',
    quote:
      "bypassing the card won't do anything, we need to hack the 1080p ASCII panel!",
  },
  {
    firstName: 'Hosea',
    lastName: 'Herzog',
    address: '95688 Ada Walk',
    state: 'Alabama',
    phoneNumber: '1-330-864-0222 x01172',
    lastLogin: '2022-08-31T20:33:28.574Z',
    favoriteMusic: 'Soul',
    favoriteSong: 'Dance to the Music',
    quote:
      "I'll synthesize the cross-platform ADP card, that should sensor the USB firewall!",
  },
  {
    firstName: 'Dillan',
    lastName: 'Effertz',
    address: '94317 Hahn Causeway',
    state: 'New York',
    phoneNumber: '660-433-6667',
    lastLogin: '2020-12-02T02:03:50.082Z',
    favoriteMusic: 'Funk',
    favoriteSong: "Lookin' Out My Back Door",
    quote:
      "indexing the microchip won't do anything, we need to copy the digital GB driver!",
  },
  {
    firstName: 'Ambrose',
    lastName: 'Considine',
    address: '365 Fatima Cape',
    state: 'Washington',
    phoneNumber: '(628) 694-0650',
    lastLogin: '2022-11-29T11:26:09.395Z',
    favoriteMusic: 'Soul',
    favoriteSong: "I Love Rock 'n' Roll",
    quote: "You can't navigate the card without indexing the haptic HEX array!",
  },
  {
    firstName: 'Domenick',
    lastName: 'Runte',
    address: '07821 Boyle Mountain',
    state: 'New York',
    phoneNumber: '444-660-8840',
    lastLogin: '2021-06-23T02:44:17.754Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'The Letter',
    quote:
      'The UDP program is down, navigate the open-source pixel so we can calculate the SMTP panel!',
  },
  {
    firstName: 'Izaiah',
    lastName: 'Renner',
    address: '286 Kuphal Circles',
    state: 'Wyoming',
    phoneNumber: '(350) 379-3779 x15509',
    lastLogin: '2020-08-23T00:06:00.466Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'Like a Rolling Stone',
    quote:
      'Try to reboot the DNS circuit, maybe it will back up the cross-platform pixel!',
  },
  {
    firstName: 'Ricardo',
    lastName: 'Ziemann',
    address: '66351 Ethan Light',
    state: 'Minnesota',
    phoneNumber: '(939) 926-9074',
    lastLogin: '2021-08-01T09:45:40.069Z',
    favoriteMusic: 'Latin',
    favoriteSong: "Papa's Got a Brand New Bag",
    quote:
      'If we connect the application, we can get to the USB array through the digital HTTP microchip!',
  },
  {
    firstName: 'Clement',
    lastName: 'Cronin',
    address: '60065 Chris Knoll',
    state: 'Nebraska',
    phoneNumber: '(981) 319-5150 x92726',
    lastLogin: '2022-04-05T21:20:30.512Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Need You Tonight',
    quote:
      'If we bypass the bus, we can get to the UTF8 driver through the open-source GB bus!',
  },
  {
    firstName: 'Bobby',
    lastName: 'Schuster',
    address: '555 Mann Trace',
    state: 'Arizona',
    phoneNumber: '432-605-5021',
    lastLogin: '2020-07-23T16:01:04.026Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Frenesi',
    quote:
      'Use the bluetooth HEX driver, then you can hack the redundant array!',
  },
  {
    firstName: 'Alfreda',
    lastName: 'Sporer',
    address: '068 Nader Mountain',
    state: 'New Hampshire',
    phoneNumber: '940-724-6142',
    lastLogin: '2021-02-03T14:18:32.112Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Need You Now',
    quote:
      "bypassing the protocol won't do anything, we need to copy the virtual IB port!",
  },
  {
    firstName: 'Gussie',
    lastName: 'Walter',
    address: '58461 Pat Grove',
    state: 'Alabama',
    phoneNumber: '520-922-7671',
    lastLogin: '2022-02-28T16:51:11.235Z',
    favoriteMusic: 'Reggae',
    favoriteSong: "Pistol Packin' Mama",
    quote:
      'The SDD alarm is down, bypass the digital interface so we can copy the JSON card!',
  },
  {
    firstName: 'Javier',
    lastName: 'Douglas',
    address: '162 Pacocha Ranch',
    state: 'New York',
    phoneNumber: '(370) 993-8299',
    lastLogin: '2021-07-24T02:38:50.640Z',
    favoriteMusic: 'World',
    favoriteSong: 'What Goes Around Comes Around',
    quote:
      "You can't generate the system without bypassing the primary XSS firewall!",
  },
  {
    firstName: 'Sydney',
    lastName: 'Armstrong',
    address: '725 Stracke Landing',
    state: 'Mississippi',
    phoneNumber: '910.942.8141',
    lastLogin: '2019-09-18T01:17:49.184Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Weak',
    quote:
      'If we index the sensor, we can get to the AGP capacitor through the online VGA capacitor!',
  },
  {
    firstName: 'Justine',
    lastName: 'Langworth',
    address: '772 Casimer Shoal',
    state: 'South Dakota',
    phoneNumber: '(350) 810-1145',
    lastLogin: '2020-08-03T16:43:41.496Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Mood Indigo',
    quote:
      'Try to calculate the TCP monitor, maybe it will transmit the auxiliary card!',
  },
  {
    firstName: 'Anabel',
    lastName: 'Leannon',
    address: '51230 Dewayne Camp',
    state: 'Kansas',
    phoneNumber: '1-888-752-3953',
    lastLogin: '2020-06-11T11:33:12.595Z',
    favoriteMusic: 'Country',
    favoriteSong: 'We Are Family',
    quote:
      "I'll quantify the online DRAM protocol, that should panel the GB capacitor!",
  },
  {
    firstName: 'Ally',
    lastName: 'Goodwin',
    address: '707 Howe Mountains',
    state: 'West Virginia',
    phoneNumber: '1-786-215-5832 x4409',
    lastLogin: '2020-09-03T17:43:12.049Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'You Make Me Feel Brand New',
    quote:
      'Try to quantify the CSS interface, maybe it will synthesize the wireless capacitor!',
  },
  {
    firstName: 'Tianna',
    lastName: 'Lang',
    address: '200 Labadie Vista',
    state: 'Montana',
    phoneNumber: '697-639-3479 x6460',
    lastLogin: '2020-05-22T10:32:45.323Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Sweet Georgia Brown',
    quote:
      'Use the digital SQL port, then you can transmit the virtual microchip!',
  },
  {
    firstName: 'Noemi',
    lastName: 'Marquardt',
    address: '8239 Paucek Prairie',
    state: 'North Carolina',
    phoneNumber: '1-677-610-6588',
    lastLogin: '2021-01-24T03:05:56.525Z',
    favoriteMusic: 'Pop',
    favoriteSong: "You're So Vain",
    quote: 'We need to synthesize the open-source FTP circuit!',
  },
  {
    firstName: 'Leonardo',
    lastName: 'Sawayn',
    address: '12643 Howell Locks',
    state: 'Missouri',
    phoneNumber: '283-273-3920 x41098',
    lastLogin: '2024-01-07T23:27:43.979Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Layla',
    quote:
      "overriding the bandwidth won't do anything, we need to back up the bluetooth HTTP pixel!",
  },
  {
    firstName: 'Melany',
    lastName: 'Corkery',
    address: '333 Upton Manor',
    state: 'Arkansas',
    phoneNumber: '(826) 688-1496 x638',
    lastLogin: '2019-12-25T23:24:07.344Z',
    favoriteMusic: 'Jazz',
    favoriteSong: "Papa's Got a Brand New Bag",
    quote:
      "You can't reboot the array without quantifying the redundant AI feed!",
  },
  {
    firstName: 'Terence',
    lastName: 'McLaughlin',
    address: '3742 Araceli Estate',
    state: 'Arkansas',
    phoneNumber: '(212) 956-0631',
    lastLogin: '2022-02-02T00:15:28.863Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Keep On Loving You',
    quote:
      "compressing the hard drive won't do anything, we need to navigate the primary HTTP card!",
  },
  {
    firstName: 'Jaime',
    lastName: 'Block',
    address: '4862 Estelle Hill',
    state: 'Georgia',
    phoneNumber: '897-843-3047 x0425',
    lastLogin: '2019-08-26T10:44:40.364Z',
    favoriteMusic: 'Soul',
    favoriteSong: "Jessie's Girl",
    quote: 'We need to copy the online COM pixel!',
  },
  {
    firstName: 'Bernita',
    lastName: 'Hagenes',
    address: '53797 Hirthe Hills',
    state: 'Pennsylvania',
    phoneNumber: '814.285.1779 x462',
    lastLogin: '2021-05-10T03:42:34.504Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Give Me Everything',
    quote:
      'If we hack the hard drive, we can get to the RSS array through the back-end CSS alarm!',
  },
  {
    firstName: 'Friedrich',
    lastName: 'Bergstrom',
    address: '90573 Kihn Parkway',
    state: 'Louisiana',
    phoneNumber: '1-869-704-2983',
    lastLogin: '2020-01-07T12:18:19.912Z',
    favoriteMusic: 'Pop',
    favoriteSong: 'If (They Made Me a King)',
    quote:
      "programming the port won't do anything, we need to calculate the open-source ASCII card!",
  },
  {
    firstName: 'Sarina',
    lastName: 'Gislason',
    address: '00854 Doyle Road',
    state: 'Idaho',
    phoneNumber: '(683) 305-5712',
    lastLogin: '2022-08-23T10:17:52.549Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Paperback Writer',
    quote:
      'Try to quantify the GB capacitor, maybe it will calculate the 1080p matrix!',
  },
  {
    firstName: 'Florian',
    lastName: 'Marks',
    address: '46979 Padberg Divide',
    state: 'Mississippi',
    phoneNumber: '(463) 238-4575 x226',
    lastLogin: '2020-11-25T16:12:32.048Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Paper Planes',
    quote:
      'The ASCII matrix is down, connect the multi-byte array so we can parse the XML pixel!',
  },
  {
    firstName: 'Clare',
    lastName: 'Carter',
    address: '979 Berge Isle',
    state: 'New Mexico',
    phoneNumber: '895-659-5983',
    lastLogin: '2019-04-25T19:26:45.034Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Hungry Heart',
    quote:
      'Use the mobile SAS panel, then you can calculate the 1080p circuit!',
  },
  {
    firstName: 'Mariam',
    lastName: 'Fritsch',
    address: '246 Tara Mews',
    state: 'Arkansas',
    phoneNumber: '1-851-297-9371 x2937',
    lastLogin: '2021-01-26T23:59:59.607Z',
    favoriteMusic: 'Funk',
    favoriteSong: "I've Heard That Song Before",
    quote: "You can't parse the monitor without copying the 1080p SMS system!",
  },
  {
    firstName: 'Jamel',
    lastName: 'Balistreri',
    address: '1702 Reinhold Crossroad',
    state: 'New York',
    phoneNumber: '382.405.3098',
    lastLogin: '2020-11-15T05:12:40.001Z',
    favoriteMusic: 'Non Music',
    favoriteSong: "Don't Be Cruel",
    quote:
      'Use the wireless SSL bandwidth, then you can copy the solid state bandwidth!',
  },
  {
    firstName: 'Alexie',
    lastName: 'Blanda',
    address: '899 Mayer Forge',
    state: 'Ohio',
    phoneNumber: '1-213-660-5875 x311',
    lastLogin: '2023-12-17T18:45:13.644Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Stairway to Heaven',
    quote:
      'If we reboot the capacitor, we can get to the HTTP transmitter through the primary RSS system!',
  },
  {
    firstName: 'Cecilia',
    lastName: 'Kirlin',
    address: '887 Legros Forest',
    state: 'Texas',
    phoneNumber: '(463) 229-3940 x7543',
    lastLogin: '2019-12-18T20:31:16.179Z',
    favoriteMusic: 'Soul',
    favoriteSong: "I Still Haven't Found What I'm Looking For",
    quote:
      "compressing the matrix won't do anything, we need to quantify the cross-platform HEX pixel!",
  },
  {
    firstName: 'Retta',
    lastName: 'Gaylord',
    address: '22556 Johathan Inlet',
    state: 'Nebraska',
    phoneNumber: '1-618-666-7937',
    lastLogin: '2019-12-16T15:12:19.121Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Pony Time',
    quote:
      'Try to compress the CLI pixel, maybe it will input the haptic feed!',
  },
  {
    firstName: 'Damon',
    lastName: 'Conroy',
    address: '5891 Darius Ways',
    state: 'Kentucky',
    phoneNumber: '723.651.0869 x86999',
    lastLogin: '2023-12-13T09:31:21.951Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Coming Up',
    quote:
      'Use the auxiliary JBOD alarm, then you can generate the auxiliary pixel!',
  },
  {
    firstName: 'Jerrod',
    lastName: 'Roberts',
    address: '97199 Narciso Mountain',
    state: 'Wyoming',
    phoneNumber: '1-662-481-8607',
    lastLogin: '2023-08-07T15:45:36.979Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Boulevard of Broken Dreams',
    quote: 'We need to reboot the neural IB card!',
  },
  {
    firstName: 'Otilia',
    lastName: 'Schamberger',
    address: '02131 Juvenal Squares',
    state: 'West Virginia',
    phoneNumber: '1-900-962-9499',
    lastLogin: '2019-09-24T11:47:38.258Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Hey Paula',
    quote:
      "You can't transmit the driver without generating the bluetooth RSS alarm!",
  },
  {
    firstName: 'Madilyn',
    lastName: 'Ratke',
    address: '2287 Howell Ways',
    state: 'West Virginia',
    phoneNumber: '1-241-356-6434',
    lastLogin: '2021-12-18T02:54:18.617Z',
    favoriteMusic: 'Classical',
    favoriteSong: "Puttin' on the Ritz",
    quote:
      "indexing the interface won't do anything, we need to input the optical SMS matrix!",
  },
  {
    firstName: 'Merritt',
    lastName: 'Tillman',
    address: '6906 Ahmed Vista',
    state: 'Wyoming',
    phoneNumber: '(830) 387-9321',
    lastLogin: '2021-04-12T19:29:16.634Z',
    favoriteMusic: 'World',
    favoriteSong: '(Let Me Be Your) Teddy Bear',
    quote:
      'The GB card is down, navigate the virtual panel so we can hack the AI sensor!',
  },
  {
    firstName: 'Lenna',
    lastName: 'Kilback',
    address: '7565 Dicki Mountains',
    state: 'Montana',
    phoneNumber: '(437) 317-0476 x9463',
    lastLogin: '2021-08-20T03:12:29.217Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Viva La Vida',
    quote:
      "copying the feed won't do anything, we need to calculate the auxiliary PNG sensor!",
  },
  {
    firstName: 'Justice',
    lastName: 'Wisozk',
    address: '632 Ahmed Camp',
    state: 'Pennsylvania',
    phoneNumber: '1-594-770-7724 x090',
    lastLogin: '2020-07-29T06:29:11.647Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Save the Last Dance For Me',
    quote: 'We need to compress the open-source IP application!',
  },
  {
    firstName: 'Laurianne',
    lastName: 'Ledner',
    address: '76981 Spencer Walks',
    state: 'Oklahoma',
    phoneNumber: '(685) 701-3169',
    lastLogin: '2023-03-22T17:41:44.981Z',
    favoriteMusic: 'Pop',
    favoriteSong: "Don't Let the Stars Get in Your Eyes",
    quote:
      "I'll hack the digital VGA transmitter, that should bus the RSS capacitor!",
  },
  {
    firstName: 'Mossie',
    lastName: 'Prosacco',
    address: '9713 Mante Isle',
    state: 'Delaware',
    phoneNumber: '(231) 851-7102',
    lastLogin: '2020-04-04T18:48:32.147Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: "Walk Don't Run",
    quote:
      'Use the optical SSL microchip, then you can generate the open-source card!',
  },
  {
    firstName: 'Faye',
    lastName: 'Bashirian',
    address: '01586 Stamm Harbors',
    state: 'Alaska',
    phoneNumber: '769-497-8752',
    lastLogin: '2020-04-26T03:43:26.581Z',
    favoriteMusic: 'Funk',
    favoriteSong: "Makin' Whoopee",
    quote:
      'Use the open-source THX program, then you can reboot the primary panel!',
  },
  {
    firstName: 'Myra',
    lastName: 'Jenkins',
    address: '201 Schowalter Plaza',
    state: 'Maryland',
    phoneNumber: '(569) 376-4319 x92789',
    lastLogin: '2022-08-10T15:03:00.847Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'American Woman',
    quote:
      "backing up the bandwidth won't do anything, we need to reboot the digital ASCII monitor!",
  },
  {
    firstName: 'Wyatt',
    lastName: 'Macejkovic',
    address: '6808 Miracle Isle',
    state: 'Nebraska',
    phoneNumber: '328.615.4206',
    lastLogin: '2021-08-26T11:32:17.150Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'When You Wish Upon a Star',
    quote:
      'Try to override the AI program, maybe it will calculate the bluetooth panel!',
  },
  {
    firstName: 'Kamren',
    lastName: 'Blanda',
    address: '1674 Mueller Pass',
    state: 'Idaho',
    phoneNumber: '1-907-688-9197',
    lastLogin: '2023-03-27T01:40:33.020Z',
    favoriteMusic: 'Pop',
    favoriteSong: 'Every Breath You Take',
    quote:
      'Use the optical ADP hard drive, then you can bypass the open-source capacitor!',
  },
  {
    firstName: 'Earl',
    lastName: 'Fadel',
    address: '692 Erdman Lock',
    state: 'Missouri',
    phoneNumber: '(738) 457-8668',
    lastLogin: '2019-11-24T21:49:57.663Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: 'Feel Like Making Love',
    quote: 'We need to compress the auxiliary PCI alarm!',
  },
  {
    firstName: 'Floyd',
    lastName: 'Quitzon',
    address: '4501 Bernhard Trafficway',
    state: 'Wyoming',
    phoneNumber: '345-252-3993 x137',
    lastLogin: '2020-04-28T04:01:49.595Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Your Song',
    quote:
      'If we program the protocol, we can get to the ADP alarm through the virtual PCI circuit!',
  },
  {
    firstName: 'Verlie',
    lastName: 'Blick',
    address: '448 Mandy Stream',
    state: 'Iowa',
    phoneNumber: '851.213.1056 x05869',
    lastLogin: '2021-08-19T22:36:17.240Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Fast Car',
    quote:
      'Try to reboot the JSON hard drive, maybe it will reboot the online protocol!',
  },
  {
    firstName: 'Boyd',
    lastName: 'Lehner',
    address: '1745 Patricia Trail',
    state: 'Georgia',
    phoneNumber: '1-823-463-7983',
    lastLogin: '2021-05-20T10:03:37.877Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Whatcha Say',
    quote:
      'Use the online HDD port, then you can compress the redundant circuit!',
  },
  {
    firstName: 'Vaughn',
    lastName: 'Altenwerth',
    address: '86164 Stamm Trail',
    state: 'Rhode Island',
    phoneNumber: '387.658.0455',
    lastLogin: '2020-03-27T20:24:35.946Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'I Got You (I Feel Good)',
    quote:
      'The SAS capacitor is down, synthesize the mobile monitor so we can parse the SDD sensor!',
  },
  {
    firstName: 'Dion',
    lastName: 'Dicki',
    address: '906 Hoeger Circles',
    state: 'Tennessee',
    phoneNumber: '(620) 402-0926 x2534',
    lastLogin: '2019-12-31T16:23:51.835Z',
    favoriteMusic: 'Folk',
    favoriteSong: "Don't You (Forget About Me)",
    quote:
      'Try to parse the VGA sensor, maybe it will synthesize the haptic application!',
  },
  {
    firstName: 'Maxwell',
    lastName: 'Turcotte',
    address: '14101 Emard Terrace',
    state: 'Oklahoma',
    phoneNumber: '1-982-446-5308 x464',
    lastLogin: '2021-12-25T15:41:17.325Z',
    favoriteMusic: 'World',
    favoriteSong: 'Dilemma',
    quote:
      "backing up the alarm won't do anything, we need to input the back-end PCI microchip!",
  },
  {
    firstName: 'Clarabelle',
    lastName: 'Johnston',
    address: '5691 Rogahn Junctions',
    state: 'New York',
    phoneNumber: '1-355-926-0460',
    lastLogin: '2021-03-09T19:47:09.723Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'So Much in Love',
    quote:
      "generating the array won't do anything, we need to override the redundant DRAM bus!",
  },
  {
    firstName: 'Jace',
    lastName: 'Yost',
    address: '826 Martin Flats',
    state: 'Delaware',
    phoneNumber: '(506) 572-8522 x174',
    lastLogin: '2019-06-05T00:26:57.560Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Physical',
    quote:
      "indexing the pixel won't do anything, we need to calculate the primary ADP monitor!",
  },
  {
    firstName: 'Justice',
    lastName: 'Bartoletti',
    address: '13767 Nicole Trace',
    state: 'Rhode Island',
    phoneNumber: '958-391-0473 x05450',
    lastLogin: '2022-11-23T22:18:26.108Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Hanging by a Moment',
    quote: 'Use the 1080p GB system, then you can hack the back-end bandwidth!',
  },
  {
    firstName: 'Rodrigo',
    lastName: 'Kozey',
    address: '48814 Kilback Overpass',
    state: 'Alaska',
    phoneNumber: '1-256-284-6866',
    lastLogin: '2021-11-08T10:59:59.332Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Runaway',
    quote:
      'If we program the hard drive, we can get to the THX card through the open-source THX hard drive!',
  },
  {
    firstName: 'Jaida',
    lastName: 'Barrows',
    address: '52318 Fay Knoll',
    state: 'Maryland',
    phoneNumber: '975.822.1015',
    lastLogin: '2019-06-28T05:06:13.564Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Harbour Lights',
    quote: 'We need to transmit the digital SDD firewall!',
  },
  {
    firstName: 'Kayleigh',
    lastName: "O'Connell",
    address: '178 Fermin Fall',
    state: 'New Mexico',
    phoneNumber: '1-602-265-9742 x208',
    lastLogin: '2021-01-05T16:53:36.245Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Stars & Stripes Forever',
    quote:
      'Try to hack the GB monitor, maybe it will copy the open-source sensor!',
  },
  {
    firstName: 'Sibyl',
    lastName: 'Beahan',
    address: '841 Nat Mills',
    state: 'Maine',
    phoneNumber: '1-998-680-4926',
    lastLogin: '2019-06-08T13:39:38.657Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Poker Face',
    quote:
      'If we input the hard drive, we can get to the SMS bandwidth through the digital HDD system!',
  },
  {
    firstName: 'Amir',
    lastName: 'Kreiger',
    address: '811 Geovanni Green',
    state: 'Maryland',
    phoneNumber: '948-816-0748',
    lastLogin: '2023-08-29T10:43:52.528Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Smoke Gets in Your Eyes',
    quote:
      'The JBOD feed is down, bypass the wireless port so we can index the USB bandwidth!',
  },
  {
    firstName: 'Freddie',
    lastName: 'Pouros',
    address: '69596 Ritchie Highway',
    state: 'Texas',
    phoneNumber: '685.639.8084',
    lastLogin: '2021-10-10T09:51:56.099Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Just Dance',
    quote: 'We need to generate the bluetooth SAS protocol!',
  },
  {
    firstName: 'Luther',
    lastName: 'Weissnat',
    address: '21870 Doyle Plains',
    state: 'Oklahoma',
    phoneNumber: '906.646.5001 x5485',
    lastLogin: '2019-08-14T03:03:57.645Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'She Loves You',
    quote:
      'Use the multi-byte ASCII matrix, then you can index the auxiliary circuit!',
  },
  {
    firstName: 'Jazlyn',
    lastName: 'Tromp',
    address: '02223 Gerhold Lodge',
    state: 'Texas',
    phoneNumber: '620.609.8021',
    lastLogin: '2023-05-17T21:46:29.440Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Kiss',
    quote:
      'The SAS hard drive is down, hack the solid state sensor so we can reboot the API alarm!',
  },
  {
    firstName: 'Monroe',
    lastName: 'Gulgowski',
    address: '6507 Steuber Pass',
    state: 'Pennsylvania',
    phoneNumber: '(566) 588-6599 x811',
    lastLogin: '2020-10-09T00:23:59.023Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'I Will Always Love You',
    quote:
      "backing up the capacitor won't do anything, we need to copy the 1080p ADP alarm!",
  },
  {
    firstName: 'Braeden',
    lastName: 'Okuneva',
    address: '89598 Kshlerin Road',
    state: 'New Jersey',
    phoneNumber: '291-598-8359',
    lastLogin: '2019-01-05T00:28:30.113Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Battle of New Orleans',
    quote:
      'The SSD sensor is down, hack the redundant monitor so we can input the TCP driver!',
  },
  {
    firstName: 'Teagan',
    lastName: 'Gerhold',
    address: '205 Buster Plaza',
    state: 'Iowa',
    phoneNumber: '1-871-232-7926',
    lastLogin: '2022-12-20T01:35:10.978Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Roll Over Beethoven',
    quote:
      "copying the panel won't do anything, we need to parse the cross-platform RSS circuit!",
  },
  {
    firstName: 'Helga',
    lastName: 'Franey',
    address: '56005 Kulas Harbor',
    state: 'Vermont',
    phoneNumber: '453-807-6073',
    lastLogin: '2022-08-13T04:20:28.462Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Brand New Key',
    quote:
      "I'll synthesize the redundant HEX matrix, that should panel the PCI feed!",
  },
  {
    firstName: 'Roma',
    lastName: 'Klein',
    address: '65176 Nola Vista',
    state: 'New Mexico',
    phoneNumber: '767-945-8529 x8275',
    lastLogin: '2021-06-11T14:12:40.224Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Love Letters in the Sand',
    quote:
      'Try to navigate the TLS transmitter, maybe it will calculate the multi-byte matrix!',
  },
  {
    firstName: 'Marquise',
    lastName: 'Cummerata',
    address: '398 Theresia View',
    state: 'Louisiana',
    phoneNumber: '1-525-342-0154 x170',
    lastLogin: '2023-09-26T08:53:24.365Z',
    favoriteMusic: 'World',
    favoriteSong: 'On the Atchison',
    quote:
      'Use the wireless TCP transmitter, then you can navigate the multi-byte interface!',
  },
  {
    firstName: 'Jed',
    lastName: 'Hayes',
    address: '63640 Donnelly Rue',
    state: 'Hawaii',
    phoneNumber: '(280) 208-8411 x15197',
    lastLogin: '2021-04-12T05:18:09.607Z',
    favoriteMusic: 'World',
    favoriteSong: 'Come Together',
    quote: 'We need to hack the primary RSS card!',
  },
  {
    firstName: 'Caleb',
    lastName: 'Mante',
    address: '845 Franecki Terrace',
    state: 'Rhode Island',
    phoneNumber: '1-807-393-4906',
    lastLogin: '2020-07-11T17:54:22.591Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Daydream Believer',
    quote:
      'Use the solid state XML matrix, then you can synthesize the primary feed!',
  },
  {
    firstName: 'Cameron',
    lastName: 'Brakus',
    address: '203 Cormier Hill',
    state: 'Tennessee',
    phoneNumber: '580-437-1892',
    lastLogin: '2022-08-21T13:44:53.414Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: 'Stand By Me',
    quote:
      'The SAS interface is down, connect the mobile array so we can index the TCP bus!',
  },
  {
    firstName: 'Allie',
    lastName: 'Feeney',
    address: '293 Larson Rest',
    state: 'New York',
    phoneNumber: '936-527-7160',
    lastLogin: '2023-10-16T00:11:07.240Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'Wannabe',
    quote:
      'If we program the monitor, we can get to the ASCII hard drive through the open-source THX panel!',
  },
  {
    firstName: 'Shanon',
    lastName: 'Oberbrunner',
    address: '03724 Ocie Avenue',
    state: 'Mississippi',
    phoneNumber: '915-519-4900 x055',
    lastLogin: '2021-03-06T06:20:32.593Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'People',
    quote:
      "I'll back up the online HEX driver, that should monitor the CLI application!",
  },
  {
    firstName: 'Lauriane',
    lastName: 'Connelly',
    address: '258 Torp Loaf',
    state: 'New York',
    phoneNumber: '752.333.1992',
    lastLogin: '2020-08-08T23:06:09.102Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Hound Dog',
    quote:
      'If we calculate the alarm, we can get to the CSS bandwidth through the solid state OCR card!',
  },
  {
    firstName: 'Jolie',
    lastName: 'Pacocha',
    address: '574 Lueilwitz Forge',
    state: 'Georgia',
    phoneNumber: '1-255-312-1232',
    lastLogin: '2021-05-12T22:06:07.014Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'You Belong to Me',
    quote:
      "You can't transmit the panel without quantifying the multi-byte XML interface!",
  },
  {
    firstName: 'Darwin',
    lastName: 'Schinner',
    address: '6641 Jerde Divide',
    state: 'Pennsylvania',
    phoneNumber: '(449) 752-5371',
    lastLogin: '2020-12-06T15:03:06.356Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Hey There Delilah',
    quote:
      'Use the open-source JBOD transmitter, then you can transmit the optical protocol!',
  },
  {
    firstName: 'Estefania',
    lastName: 'Quigley',
    address: '0226 Ali Expressway',
    state: 'Oregon',
    phoneNumber: '518-499-6231',
    lastLogin: '2022-09-21T11:06:57.598Z',
    favoriteMusic: 'World',
    favoriteSong: "You're Beautiful",
    quote:
      "synthesizing the capacitor won't do anything, we need to reboot the digital HEX port!",
  },
  {
    firstName: 'Raymundo',
    lastName: 'Treutel',
    address: '228 Kuhlman Freeway',
    state: 'Tennessee',
    phoneNumber: '974.936.1957 x70558',
    lastLogin: '2022-11-16T23:36:51.178Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Wild Wild West',
    quote:
      "You can't connect the protocol without bypassing the auxiliary SAS firewall!",
  },
  {
    firstName: 'Deangelo',
    lastName: 'Blick',
    address: '029 Violette Station',
    state: 'Missouri',
    phoneNumber: '(741) 405-3853',
    lastLogin: '2019-08-04T11:02:15.375Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Over the Rainbow',
    quote:
      'Try to override the PNG feed, maybe it will parse the optical pixel!',
  },
  {
    firstName: 'Sarah',
    lastName: 'Labadie',
    address: '503 Leopoldo Cove',
    state: 'Colorado',
    phoneNumber: '204.745.5814 x54620',
    lastLogin: '2020-08-12T14:44:21.596Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'The Girl From Ipanema',
    quote:
      "connecting the transmitter won't do anything, we need to program the bluetooth SQL circuit!",
  },
  {
    firstName: 'Cordell',
    lastName: 'Dicki',
    address: '849 Malvina Mount',
    state: 'Oklahoma',
    phoneNumber: '424-610-2775 x56165',
    lastLogin: '2021-07-18T17:33:23.297Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Me & Mrs Jones',
    quote:
      "I'll quantify the 1080p SSD port, that should transmitter the GB monitor!",
  },
  {
    firstName: 'Ibrahim',
    lastName: 'Torphy',
    address: '566 Aleen Ramp',
    state: 'New Mexico',
    phoneNumber: '1-500-693-0802 x4695',
    lastLogin: '2019-12-12T14:01:04.034Z',
    favoriteMusic: 'World',
    favoriteSong: 'Mr Tambourine Man',
    quote: 'We need to index the neural OCR bus!',
  },
  {
    firstName: 'Nella',
    lastName: 'Gerlach',
    address: '2281 Leffler Village',
    state: 'Kentucky',
    phoneNumber: '659-865-3149 x82226',
    lastLogin: '2020-03-08T00:31:00.960Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Louie Louie',
    quote:
      'Try to synthesize the DNS firewall, maybe it will connect the back-end panel!',
  },
  {
    firstName: 'Madalyn',
    lastName: 'Wintheiser',
    address: '575 Wintheiser Common',
    state: 'West Virginia',
    phoneNumber: '349.669.3708 x7744',
    lastLogin: '2023-06-03T12:51:49.671Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Crying',
    quote:
      'Try to index the USB alarm, maybe it will transmit the multi-byte firewall!',
  },
  {
    firstName: 'Heidi',
    lastName: 'Krajcik',
    address: '38559 Hailie Grove',
    state: 'Washington',
    phoneNumber: '1-559-717-2720 x558',
    lastLogin: '2019-11-18T16:20:03.743Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'The Tracks of My Tears',
    quote:
      'Try to transmit the TLS capacitor, maybe it will bypass the solid state feed!',
  },
  {
    firstName: 'Veronica',
    lastName: 'Flatley',
    address: '08269 Rowe Hill',
    state: 'Utah',
    phoneNumber: '1-941-655-9866 x6133',
    lastLogin: '2023-08-09T19:27:31.695Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Ballad of the Green Berets',
    quote:
      'The HEX matrix is down, index the optical circuit so we can override the PCI driver!',
  },
  {
    firstName: 'Kimberly',
    lastName: "O'Connell",
    address: '14894 Ashlynn Lock',
    state: 'Rhode Island',
    phoneNumber: '1-484-949-4663',
    lastLogin: '2020-08-30T02:13:55.811Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Yellow Rose of Texas',
    quote:
      'Try to input the PCI microchip, maybe it will calculate the multi-byte alarm!',
  },
  {
    firstName: 'Jannie',
    lastName: 'Douglas',
    address: '74809 Mraz Trail',
    state: 'Oregon',
    phoneNumber: '461.287.3248 x66090',
    lastLogin: '2022-03-11T12:54:17.939Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'That Old Black Magic',
    quote:
      'Try to override the ASCII circuit, maybe it will hack the online card!',
  },
  {
    firstName: 'Zoila',
    lastName: 'Connelly',
    address: '3840 Abel Manor',
    state: 'Wisconsin',
    phoneNumber: '(720) 486-1238 x539',
    lastLogin: '2022-08-16T08:11:12.571Z',
    favoriteMusic: 'Jazz',
    favoriteSong: "Don't Speak",
    quote:
      'Try to parse the UTF8 interface, maybe it will index the redundant monitor!',
  },
  {
    firstName: 'Dino',
    lastName: 'Nader',
    address: '96105 Clarissa Spring',
    state: 'Texas',
    phoneNumber: '1-690-682-5517 x506',
    lastLogin: '2019-05-20T00:39:18.123Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Some of These Days',
    quote:
      'Use the multi-byte SSL capacitor, then you can parse the online microchip!',
  },
  {
    firstName: 'Jarrell',
    lastName: 'Klein',
    address: '28102 Vada Forks',
    state: 'Rhode Island',
    phoneNumber: '818.967.4980',
    lastLogin: '2023-12-06T06:23:48.908Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Tennessee Waltz',
    quote:
      'Try to transmit the TCP bus, maybe it will back up the multi-byte bandwidth!',
  },
  {
    firstName: 'Curt',
    lastName: 'Stamm',
    address: '4438 Lina Rest',
    state: 'New Jersey',
    phoneNumber: '506-312-7423 x470',
    lastLogin: '2019-09-22T07:07:13.980Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Funkytown',
    quote: 'We need to connect the back-end VGA system!',
  },
  {
    firstName: 'Lela',
    lastName: 'Goodwin',
    address: '84052 Gusikowski Canyon',
    state: 'Iowa',
    phoneNumber: '1-995-348-0625',
    lastLogin: '2023-04-19T00:05:14.671Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Lady Marmalade (Voulez-Vous Coucher Aver Moi Ce Soir?)',
    quote:
      "copying the microchip won't do anything, we need to parse the wireless API bandwidth!",
  },
  {
    firstName: 'Elyse',
    lastName: 'Wuckert',
    address: '47743 Lamar Alley',
    state: 'Illinois',
    phoneNumber: '986-502-6816',
    lastLogin: '2022-12-23T11:31:23.092Z',
    favoriteMusic: 'World',
    favoriteSong: "Cathy's Clown",
    quote:
      'If we navigate the transmitter, we can get to the SSD transmitter through the back-end TCP pixel!',
  },
  {
    firstName: 'Marlen',
    lastName: 'Franey',
    address: '518 Kovacek Trail',
    state: 'Alabama',
    phoneNumber: '(466) 519-5017',
    lastLogin: '2021-08-20T19:52:39.622Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'A Tree in the Meadow',
    quote:
      "You can't generate the interface without synthesizing the digital JSON system!",
  },
  {
    firstName: 'Laury',
    lastName: 'Corkery',
    address: '77904 Victoria Pine',
    state: 'Texas',
    phoneNumber: '874.428.1541',
    lastLogin: '2022-12-14T10:28:38.718Z',
    favoriteMusic: 'Blues',
    favoriteSong: "Drop it Like It's Hot",
    quote:
      'If we generate the port, we can get to the SCSI capacitor through the optical SSL port!',
  },
  {
    firstName: 'Lincoln',
    lastName: 'Weissnat',
    address: '5898 Rolfson Cliff',
    state: 'Washington',
    phoneNumber: '1-452-236-9645',
    lastLogin: '2023-02-13T19:13:37.166Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Boom Boom Pow',
    quote:
      "bypassing the monitor won't do anything, we need to reboot the wireless RAM feed!",
  },
  {
    firstName: 'Nadia',
    lastName: 'Bernier',
    address: '78167 Windler Oval',
    state: 'Arkansas',
    phoneNumber: '517-783-7505',
    lastLogin: '2019-09-07T11:35:07.447Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Stuck On You',
    quote:
      'Try to reboot the UTF8 monitor, maybe it will connect the online alarm!',
  },
  {
    firstName: 'Malcolm',
    lastName: 'Dach',
    address: '98782 Carroll Flats',
    state: 'Pennsylvania',
    phoneNumber: '610-374-0184 x8266',
    lastLogin: '2022-08-21T22:52:11.519Z',
    favoriteMusic: 'Soul',
    favoriteSong: 'Hold On',
    quote:
      'The XSS pixel is down, copy the open-source alarm so we can program the DRAM panel!',
  },
  {
    firstName: 'Maiya',
    lastName: 'Feeney',
    address: '7803 Ortiz Shore',
    state: 'Nebraska',
    phoneNumber: '1-459-985-0817 x152',
    lastLogin: '2022-02-26T12:59:05.481Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Roll With It',
    quote: "You can't copy the port without connecting the optical SMS matrix!",
  },
  {
    firstName: 'Hal',
    lastName: 'Cronin',
    address: '914 Hellen Coves',
    state: 'Massachusetts',
    phoneNumber: '276.609.6039',
    lastLogin: '2022-12-05T16:57:41.905Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Bohemian Rhapsody',
    quote:
      'Use the auxiliary SSD firewall, then you can quantify the digital port!',
  },
  {
    firstName: 'Buster',
    lastName: 'Jacobs',
    address: '3974 Kassandra Prairie',
    state: 'Montana',
    phoneNumber: '(678) 685-1364 x02125',
    lastLogin: '2019-02-10T09:02:18.513Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Promiscuous',
    quote:
      'Try to index the TLS card, maybe it will back up the digital sensor!',
  },
  {
    firstName: 'Garland',
    lastName: 'Okuneva',
    address: '7066 Catalina Prairie',
    state: 'Rhode Island',
    phoneNumber: '336-881-0669 x031',
    lastLogin: '2020-03-13T23:40:23.980Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Because You Loved Me',
    quote:
      "You can't override the matrix without copying the multi-byte TLS interface!",
  },
  {
    firstName: 'Damon',
    lastName: 'Ullrich',
    address: "534 O'Conner Falls",
    state: 'Louisiana',
    phoneNumber: '1-377-497-8909',
    lastLogin: '2023-04-21T17:29:35.793Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Light My Fire',
    quote: 'Use the haptic IB feed, then you can program the neural capacitor!',
  },
  {
    firstName: 'Jordon',
    lastName: 'Steuber',
    address: '3997 Olson Lights',
    state: 'West Virginia',
    phoneNumber: '(834) 340-5699',
    lastLogin: '2023-08-04T00:00:21.723Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Wind Beneath My Wings',
    quote:
      'Try to copy the UTF8 capacitor, maybe it will navigate the solid state matrix!',
  },
  {
    firstName: 'Amparo',
    lastName: 'Volkman',
    address: '434 Shaun Mill',
    state: 'Michigan',
    phoneNumber: '1-389-763-1458',
    lastLogin: '2019-10-08T06:38:17.524Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Hello Dolly',
    quote:
      "I'll navigate the digital SSL driver, that should interface the CSS application!",
  },
  {
    firstName: 'Brooklyn',
    lastName: 'Zemlak',
    address: '715 Schamberger Plain',
    state: 'California',
    phoneNumber: '827.857.7624 x2547',
    lastLogin: '2021-08-26T12:45:44.561Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: "Tie a Yellow Ribbon 'round the Old Oak Tree",
    quote: 'We need to index the online HDD firewall!',
  },
  {
    firstName: 'Carlos',
    lastName: 'Turner',
    address: '8309 Verlie Mount',
    state: 'Connecticut',
    phoneNumber: '479.618.0627 x01411',
    lastLogin: '2019-10-27T16:08:51.478Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Georgy Girl',
    quote:
      "generating the protocol won't do anything, we need to synthesize the back-end AGP bus!",
  },
  {
    firstName: 'Jay',
    lastName: 'Gaylord',
    address: '19697 Stewart Unions',
    state: 'Michigan',
    phoneNumber: '814.990.2558 x9948',
    lastLogin: '2021-02-05T09:38:15.983Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Help!',
    quote:
      "I'll index the solid state SSD array, that should interface the SAS monitor!",
  },
  {
    firstName: 'Jazmyne',
    lastName: 'Gibson',
    address: '3442 Everette Tunnel',
    state: 'Utah',
    phoneNumber: '542.209.3639',
    lastLogin: '2022-12-01T16:58:17.890Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Band On the Run',
    quote:
      'If we back up the circuit, we can get to the SQL array through the back-end HEX feed!',
  },
  {
    firstName: 'Chad',
    lastName: 'Bartell',
    address: '997 Alexander Village',
    state: 'Wyoming',
    phoneNumber: '1-512-366-1968',
    lastLogin: '2022-03-18T16:42:38.173Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Never Gonna Give You Up',
    quote:
      'If we reboot the microchip, we can get to the RAM matrix through the primary XSS monitor!',
  },
  {
    firstName: 'Peter',
    lastName: 'Kessler',
    address: '43711 Nolan Fort',
    state: 'Kentucky',
    phoneNumber: '408.278.2672',
    lastLogin: '2019-03-29T11:42:59.259Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: "Surfin' USA",
    quote:
      "calculating the sensor won't do anything, we need to generate the online DNS feed!",
  },
  {
    firstName: 'Joey',
    lastName: 'Koelpin',
    address: '10542 Cleveland Mills',
    state: 'Nebraska',
    phoneNumber: '649.447.7594 x978',
    lastLogin: '2020-08-12T14:53:01.164Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Love Shack',
    quote:
      'Use the mobile AI protocol, then you can bypass the open-source feed!',
  },
  {
    firstName: 'Tod',
    lastName: 'Sanford',
    address: '7653 Juwan Radial',
    state: 'Wisconsin',
    phoneNumber: '781-209-6459',
    lastLogin: '2021-03-01T19:01:04.202Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Burn',
    quote:
      'The HTTP microchip is down, bypass the online microchip so we can bypass the FTP hard drive!',
  },
  {
    firstName: 'Nakia',
    lastName: 'Moen',
    address: '75115 Donnie Way',
    state: 'Arkansas',
    phoneNumber: '845-690-1809 x274',
    lastLogin: '2021-08-28T07:11:15.930Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'You Always Hurt the One You Love',
    quote:
      "indexing the port won't do anything, we need to reboot the neural VGA alarm!",
  },
  {
    firstName: 'Lavonne',
    lastName: 'Cronin',
    address: '3545 Bulah Circles',
    state: 'Alaska',
    phoneNumber: '(381) 522-1962 x15573',
    lastLogin: '2022-02-15T14:12:30.051Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: 'Rich Girl',
    quote:
      'The TCP feed is down, back up the back-end feed so we can override the GB alarm!',
  },
  {
    firstName: 'Alfredo',
    lastName: 'Treutel',
    address: '90919 Jenkins Stravenue',
    state: 'Mississippi',
    phoneNumber: '262.483.1238 x2432',
    lastLogin: '2022-06-17T08:02:07.374Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Time of the Season',
    quote:
      'Try to transmit the RSS interface, maybe it will bypass the wireless bus!',
  },
  {
    firstName: 'Savanah',
    lastName: 'Graham',
    address: '55171 Johnston Wall',
    state: 'Washington',
    phoneNumber: '1-502-827-8410',
    lastLogin: '2019-07-15T02:35:54.206Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: "I'm Looking Over a Four Leaf Clover",
    quote: 'We need to copy the multi-byte RSS capacitor!',
  },
  {
    firstName: 'Esteban',
    lastName: 'Rosenbaum',
    address: '642 Raquel Common',
    state: 'New York',
    phoneNumber: '782-792-6555 x6278',
    lastLogin: '2022-01-27T18:17:31.455Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Sugar Sugar',
    quote:
      'Try to navigate the RAM bandwidth, maybe it will override the auxiliary application!',
  },
  {
    firstName: 'Ted',
    lastName: 'Schmeler',
    address: '83783 Alek Summit',
    state: 'Iowa',
    phoneNumber: '415.509.0261',
    lastLogin: '2023-09-14T02:05:27.338Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'A Tree in the Meadow',
    quote:
      "I'll connect the open-source TCP sensor, that should application the UDP firewall!",
  },
  {
    firstName: 'Roselyn',
    lastName: 'Doyle',
    address: '0928 Bradly Ridges',
    state: 'Georgia',
    phoneNumber: '1-726-794-4130 x43166',
    lastLogin: '2022-02-28T03:53:54.795Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'Rapture',
    quote:
      'The PNG card is down, input the redundant microchip so we can navigate the JSON bandwidth!',
  },
  {
    firstName: 'Idell',
    lastName: 'Kirlin',
    address: '8527 Hoeger Plains',
    state: 'New Jersey',
    phoneNumber: '1-261-430-1323',
    lastLogin: '2023-04-05T19:49:35.054Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Let Me Love You',
    quote:
      "programming the hard drive won't do anything, we need to connect the virtual COM firewall!",
  },
  {
    firstName: 'Oswaldo',
    lastName: 'Koepp',
    address: '000 Camden Land',
    state: 'Massachusetts',
    phoneNumber: '(485) 381-8750',
    lastLogin: '2019-10-21T01:13:04.342Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Tangerine',
    quote:
      'Use the multi-byte CSS protocol, then you can bypass the virtual firewall!',
  },
  {
    firstName: 'Raleigh',
    lastName: 'Dicki',
    address: '84142 Wiza Bridge',
    state: 'Nebraska',
    phoneNumber: '(478) 658-7018 x6805',
    lastLogin: '2020-11-02T21:57:02.432Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'She Loves You',
    quote:
      'The RAM monitor is down, override the redundant program so we can index the FTP pixel!',
  },
  {
    firstName: 'Norma',
    lastName: 'Heller',
    address: '755 Jaskolski Square',
    state: 'Connecticut',
    phoneNumber: '(295) 876-3062',
    lastLogin: '2022-02-02T19:32:15.280Z',
    favoriteMusic: 'Folk',
    favoriteSong: "Won't Get Fooled Again",
    quote:
      'The SSD program is down, calculate the solid state transmitter so we can quantify the RAM card!',
  },
  {
    firstName: 'Kayla',
    lastName: 'Herzog',
    address: '4739 Parisian Corners',
    state: 'Idaho',
    phoneNumber: '504-458-4377 x34542',
    lastLogin: '2019-12-04T01:59:04.874Z',
    favoriteMusic: 'Non Music',
    favoriteSong: "You Don't Have to Be a Star (To Be in My Show)",
    quote:
      'Try to navigate the UDP microchip, maybe it will input the mobile transmitter!',
  },
  {
    firstName: 'Adriana',
    lastName: 'Graham',
    address: '2765 Hettinger Mission',
    state: 'Nevada',
    phoneNumber: '691-938-4227',
    lastLogin: '2023-04-03T18:04:02.329Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Tha Crossroads',
    quote:
      "You can't program the driver without navigating the back-end PCI microchip!",
  },
  {
    firstName: 'Cassie',
    lastName: 'Zemlak',
    address: '10136 Brown Well',
    state: 'Mississippi',
    phoneNumber: '1-886-407-5724',
    lastLogin: '2023-05-25T08:24:56.376Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Superstition',
    quote:
      'The XML circuit is down, copy the neural system so we can input the SSD transmitter!',
  },
  {
    firstName: 'Lyric',
    lastName: 'Botsford',
    address: '9858 Bridgette Ways',
    state: 'New York',
    phoneNumber: '921-941-9707 x97387',
    lastLogin: '2020-06-18T22:49:54.879Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Always On My Mind',
    quote:
      'If we generate the system, we can get to the AGP hard drive through the optical API hard drive!',
  },
  {
    firstName: 'Jalon',
    lastName: 'Auer',
    address: '1337 Spencer Shoals',
    state: 'Arizona',
    phoneNumber: '626.664.1307 x7251',
    lastLogin: '2022-09-06T01:58:58.283Z',
    favoriteMusic: 'Reggae',
    favoriteSong: "U Can't Touch This",
    quote:
      'Try to compress the UTF8 protocol, maybe it will quantify the online sensor!',
  },
  {
    firstName: 'Ludwig',
    lastName: 'Olson',
    address: '969 Smith Isle',
    state: 'Utah',
    phoneNumber: '460.363.0230 x433',
    lastLogin: '2020-07-27T19:51:05.091Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Big Bad John',
    quote:
      'The FTP port is down, override the open-source hard drive so we can bypass the HEX circuit!',
  },
  {
    firstName: 'Bridie',
    lastName: 'Brown',
    address: '40022 Herman Fall',
    state: 'Colorado',
    phoneNumber: '(488) 464-2590 x006',
    lastLogin: '2020-08-21T00:19:41.480Z',
    favoriteMusic: 'World',
    favoriteSong: 'The Power of Love',
    quote: 'We need to quantify the neural TLS matrix!',
  },
  {
    firstName: 'Catalina',
    lastName: 'Rippin',
    address: '43734 Nitzsche Groves',
    state: 'Colorado',
    phoneNumber: '705-543-3151 x793',
    lastLogin: '2021-08-09T12:26:22.963Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: "I Can't Stop Loving You",
    quote: 'We need to connect the solid state OCR port!',
  },
  {
    firstName: 'Carolanne',
    lastName: 'Turcotte',
    address: '7259 Lockman Flats',
    state: 'Oregon',
    phoneNumber: '1-682-446-8574',
    lastLogin: '2022-06-08T09:12:20.741Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Total Eclipse of the Heart',
    quote:
      'If we back up the firewall, we can get to the UDP capacitor through the back-end SQL hard drive!',
  },
  {
    firstName: 'Scotty',
    lastName: 'Williamson',
    address: '61776 Rebeka Summit',
    state: 'Colorado',
    phoneNumber: '829-632-3726 x9232',
    lastLogin: '2020-03-06T09:18:52.685Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'All I Wanna Do',
    quote:
      "transmitting the firewall won't do anything, we need to navigate the neural TLS pixel!",
  },
  {
    firstName: 'Forest',
    lastName: 'Rau',
    address: '84797 Prohaska Route',
    state: 'Oklahoma',
    phoneNumber: '1-506-693-4479 x7363',
    lastLogin: '2022-02-13T03:51:02.882Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'My Girl',
    quote:
      'If we transmit the bandwidth, we can get to the JSON array through the redundant DNS interface!',
  },
  {
    firstName: 'Mustafa',
    lastName: 'Glover',
    address: '8784 Gilda Ferry',
    state: 'Texas',
    phoneNumber: '(221) 701-4090 x6545',
    lastLogin: '2020-03-28T22:08:14.861Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Grease',
    quote:
      'If we program the circuit, we can get to the API transmitter through the mobile CSS alarm!',
  },
  {
    firstName: 'Alexa',
    lastName: 'Schaden',
    address: '216 Bashirian Common',
    state: 'Arizona',
    phoneNumber: '(794) 997-1491',
    lastLogin: '2023-10-19T00:48:46.789Z',
    favoriteMusic: 'Rock',
    favoriteSong: '50 Ways to Leave Your Lover',
    quote:
      'Use the wireless IB port, then you can compress the bluetooth card!',
  },
  {
    firstName: 'Valentine',
    lastName: 'Weimann',
    address: '813 Augustus Spur',
    state: 'Utah',
    phoneNumber: '206.690.2919',
    lastLogin: '2020-09-30T07:09:57.228Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Because of You',
    quote: 'We need to parse the auxiliary TLS capacitor!',
  },
  {
    firstName: 'Isabell',
    lastName: 'Senger',
    address: '37201 Corkery Ranch',
    state: 'Iowa',
    phoneNumber: '1-531-713-5087',
    lastLogin: '2020-06-29T19:23:55.807Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'E.T.',
    quote:
      "I'll index the solid state XML microchip, that should transmitter the OCR alarm!",
  },
  {
    firstName: 'Jakob',
    lastName: 'Jacobs',
    address: '336 Itzel Viaduct',
    state: 'Hawaii',
    phoneNumber: '(652) 827-4708 x04803',
    lastLogin: '2019-09-17T21:17:28.501Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Red Red Wine',
    quote:
      'Try to calculate the EXE sensor, maybe it will input the optical feed!',
  },
  {
    firstName: 'Adell',
    lastName: 'Bergstrom',
    address: '3844 Cormier Island',
    state: 'Georgia',
    phoneNumber: '647-786-3685 x498',
    lastLogin: '2022-03-23T20:07:07.730Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Escape (The Pina Colada Song)',
    quote:
      "I'll parse the mobile JBOD array, that should interface the ADP array!",
  },
  {
    firstName: 'Enid',
    lastName: 'Turner',
    address: '9124 Bella Parkway',
    state: 'California',
    phoneNumber: '898.625.2245',
    lastLogin: '2023-10-02T21:37:37.848Z',
    favoriteMusic: 'Country',
    favoriteSong: 'Tik-Toc',
    quote:
      'The PNG alarm is down, transmit the mobile feed so we can program the JSON array!',
  },
  {
    firstName: 'Jazmyn',
    lastName: 'Bayer',
    address: '994 Vandervort Freeway',
    state: 'Michigan',
    phoneNumber: '1-525-851-3729',
    lastLogin: '2020-08-07T08:51:58.175Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'The Love You Save',
    quote:
      'Use the wireless AGP driver, then you can input the primary hard drive!',
  },
  {
    firstName: 'Wallace',
    lastName: 'Schultz',
    address: '991 Cynthia Islands',
    state: 'South Dakota',
    phoneNumber: '276.486.9138 x19749',
    lastLogin: '2021-12-15T20:21:59.615Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'The Sign',
    quote:
      'The IB transmitter is down, input the redundant array so we can compress the UTF8 bus!',
  },
  {
    firstName: 'Ronaldo',
    lastName: 'Bergnaum',
    address: '793 Harvey Cliffs',
    state: 'Minnesota',
    phoneNumber: '(763) 924-8113 x909',
    lastLogin: '2019-09-10T04:59:43.612Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Cheek to Cheek',
    quote:
      "You can't calculate the driver without bypassing the open-source PNG application!",
  },
  {
    firstName: 'Jamarcus',
    lastName: 'Dickens',
    address: '458 Raoul Crossing',
    state: 'Minnesota',
    phoneNumber: '1-977-491-1174 x12903',
    lastLogin: '2022-01-08T12:50:58.859Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'One',
    quote:
      "connecting the capacitor won't do anything, we need to navigate the back-end ASCII matrix!",
  },
  {
    firstName: 'Ozella',
    lastName: 'Walsh',
    address: '28623 Imani Mission',
    state: 'Iowa',
    phoneNumber: '1-803-233-1722 x94688',
    lastLogin: '2020-07-20T09:55:33.884Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Wipe Out',
    quote:
      'The UTF8 bus is down, hack the haptic application so we can transmit the DNS panel!',
  },
  {
    firstName: 'Vergie',
    lastName: 'Stokes',
    address: '57283 Dahlia Ranch',
    state: 'New York',
    phoneNumber: '1-974-656-0663 x201',
    lastLogin: '2023-01-11T05:24:46.164Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'This Ole House',
    quote:
      'Use the open-source IB panel, then you can quantify the cross-platform feed!',
  },
  {
    firstName: 'Juvenal',
    lastName: 'Rogahn',
    address: '016 Wiegand Plains',
    state: 'Florida',
    phoneNumber: '(569) 709-7816',
    lastLogin: '2020-06-15T14:11:40.649Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Swinging On a Star',
    quote:
      "navigating the bandwidth won't do anything, we need to input the online SQL driver!",
  },
  {
    firstName: 'Marisa',
    lastName: "O'Connell",
    address: '9075 Schowalter Crossing',
    state: 'Indiana',
    phoneNumber: '(368) 695-6801 x6567',
    lastLogin: '2022-01-22T20:34:36.727Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Body & Soul',
    quote:
      "I'll compress the neural HDD matrix, that should firewall the HEX application!",
  },
  {
    firstName: 'Renee',
    lastName: 'MacGyver',
    address: '28801 Melody Locks',
    state: 'South Carolina',
    phoneNumber: '217-885-0010 x51327',
    lastLogin: '2019-08-17T15:24:13.220Z',
    favoriteMusic: 'World',
    favoriteSong: "Can't Help Falling in Love",
    quote:
      'Try to synthesize the DNS bus, maybe it will synthesize the primary alarm!',
  },
  {
    firstName: 'Luz',
    lastName: 'Labadie',
    address: '7427 Marvin Lock',
    state: 'Iowa',
    phoneNumber: '1-475-395-9892',
    lastLogin: '2023-05-04T11:46:27.845Z',
    favoriteMusic: 'Pop',
    favoriteSong: 'Eve of Destruction',
    quote: 'We need to program the neural RSS alarm!',
  },
  {
    firstName: 'Thurman',
    lastName: 'Quitzon',
    address: '1451 Houston Center',
    state: 'California',
    phoneNumber: '(606) 818-4644 x897',
    lastLogin: '2023-04-24T20:08:03.415Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'This Used to Be My Playground',
    quote:
      'Try to bypass the USB interface, maybe it will parse the optical alarm!',
  },
  {
    firstName: 'Jerrold',
    lastName: 'Grant',
    address: '26488 Leonel Place',
    state: 'Massachusetts',
    phoneNumber: '1-949-823-5546 x320',
    lastLogin: '2022-09-06T01:08:43.228Z',
    favoriteMusic: 'World',
    favoriteSong: 'Chattanooga Choo Choo',
    quote:
      'If we reboot the system, we can get to the HTTP port through the bluetooth JBOD panel!',
  },
  {
    firstName: 'Charlene',
    lastName: 'Kautzer',
    address: '026 Koch Squares',
    state: 'Delaware',
    phoneNumber: '1-819-452-4832',
    lastLogin: '2021-11-12T16:22:52.339Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Kung Fu Fighting',
    quote:
      "I'll back up the solid state XSS application, that should panel the OCR driver!",
  },
  {
    firstName: 'Bennie',
    lastName: 'White',
    address: '8838 Ruthe Lodge',
    state: 'Oregon',
    phoneNumber: '1-326-766-9776 x5871',
    lastLogin: '2019-10-02T03:49:08.476Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'I Wanna Dance With Somebody (Who Loves Me)',
    quote: 'We need to index the auxiliary AGP alarm!',
  },
  {
    firstName: 'Serena',
    lastName: 'Howell',
    address: '50451 Stephanie Lane',
    state: 'North Dakota',
    phoneNumber: '494.371.8192 x3198',
    lastLogin: '2023-05-26T12:48:02.295Z',
    favoriteMusic: 'Hip Hop',
    favoriteSong: 'Crazy Little Thing Called Love',
    quote: 'We need to navigate the haptic SSL firewall!',
  },
  {
    firstName: 'Christian',
    lastName: 'Zulauf',
    address: '0536 Marcelino Stravenue',
    state: 'South Dakota',
    phoneNumber: '311.287.5546 x634',
    lastLogin: '2022-02-21T16:31:57.849Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Yeah!',
    quote:
      "I'll calculate the 1080p JBOD firewall, that should sensor the DRAM circuit!",
  },
  {
    firstName: 'Trenton',
    lastName: 'Gutmann',
    address: '1794 Friedrich Drives',
    state: 'North Dakota',
    phoneNumber: '587.472.6191 x90105',
    lastLogin: '2021-05-14T15:23:38.984Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Take On Me',
    quote:
      "I'll index the multi-byte DRAM program, that should sensor the DNS monitor!",
  },
  {
    firstName: 'Julianne',
    lastName: 'Reichert',
    address: '39854 Herman Overpass',
    state: 'Missouri',
    phoneNumber: '1-921-342-5327 x91377',
    lastLogin: '2020-10-13T21:46:43.921Z',
    favoriteMusic: 'Metal',
    favoriteSong: "Won't Get Fooled Again",
    quote:
      'The ASCII sensor is down, copy the virtual monitor so we can hack the OCR array!',
  },
  {
    firstName: 'Arne',
    lastName: 'Jerde',
    address: '73182 Camryn Mills',
    state: 'Ohio',
    phoneNumber: '1-886-609-1117 x1213',
    lastLogin: '2021-07-15T07:55:57.969Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Build Me Up Buttercup',
    quote:
      'If we copy the application, we can get to the SSL array through the online GB card!',
  },
  {
    firstName: 'Russel',
    lastName: 'Prosacco',
    address: '733 Fausto Harbors',
    state: 'Alaska',
    phoneNumber: '(768) 434-0549 x046',
    lastLogin: '2022-01-04T12:36:15.613Z',
    favoriteMusic: 'Blues',
    favoriteSong: 'Man in the Mirror',
    quote:
      "You can't program the application without indexing the bluetooth RSS port!",
  },
  {
    firstName: 'Sylvan',
    lastName: 'Pacocha',
    address: '1666 Kayden Knolls',
    state: 'Virginia',
    phoneNumber: '890.970.7412 x99529',
    lastLogin: '2023-01-13T11:38:20.489Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Tammy',
    quote: 'We need to program the optical UTF8 microchip!',
  },
  {
    firstName: 'Avis',
    lastName: 'Kemmer',
    address: '067 Dicki Spring',
    state: 'Minnesota',
    phoneNumber: '1-470-276-6628 x7318',
    lastLogin: '2020-08-03T09:30:51.310Z',
    favoriteMusic: 'Country',
    favoriteSong: 'We Will Rock You',
    quote:
      'If we index the bandwidth, we can get to the SSL matrix through the mobile RSS card!',
  },
  {
    firstName: 'Vinnie',
    lastName: 'Erdman',
    address: '266 West Parks',
    state: 'Ohio',
    phoneNumber: '295.883.0344 x9687',
    lastLogin: '2021-08-31T10:41:31.145Z',
    favoriteMusic: 'Pop',
    favoriteSong: 'Dancing Queen',
    quote: 'We need to program the auxiliary ADP port!',
  },
  {
    firstName: 'Retha',
    lastName: 'Shanahan',
    address: '92874 Burnice Rest',
    state: 'West Virginia',
    phoneNumber: '1-989-842-2804',
    lastLogin: '2021-11-01T14:04:37.080Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Leader of the Pack',
    quote:
      'If we generate the system, we can get to the JSON capacitor through the auxiliary JSON circuit!',
  },
  {
    firstName: 'Sophia',
    lastName: 'Durgan',
    address: '33093 Kris Highway',
    state: 'West Virginia',
    phoneNumber: '257-311-0156 x02940',
    lastLogin: '2023-04-16T22:04:32.445Z',
    favoriteMusic: 'Reggae',
    favoriteSong: 'Take a Bow',
    quote:
      "programming the protocol won't do anything, we need to connect the redundant OCR application!",
  },
  {
    firstName: 'Geovany',
    lastName: 'Tromp',
    address: '04085 Vesta Corners',
    state: 'Oregon',
    phoneNumber: '366.420.6148 x9787',
    lastLogin: '2020-04-08T05:16:09.002Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Here in My Heart',
    quote:
      'Try to copy the ASCII feed, maybe it will index the wireless protocol!',
  },
  {
    firstName: 'Abdullah',
    lastName: 'Williamson',
    address: '2785 Karlie Run',
    state: 'Florida',
    phoneNumber: '(689) 794-2642 x8431',
    lastLogin: '2020-08-16T20:37:23.466Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'Bye',
    quote:
      "You can't index the capacitor without backing up the open-source USB sensor!",
  },
  {
    firstName: 'Bo',
    lastName: 'Hettinger',
    address: '11099 Dare Isle',
    state: 'Florida',
    phoneNumber: '(359) 794-0686 x05810',
    lastLogin: '2022-06-25T21:03:05.811Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Rush Rush',
    quote:
      'Use the primary SMTP program, then you can calculate the 1080p microchip!',
  },
  {
    firstName: 'Lois',
    lastName: 'Reichel',
    address: '41309 Abernathy Valley',
    state: 'Rhode Island',
    phoneNumber: '(444) 941-5900 x2001',
    lastLogin: '2021-12-03T16:26:57.343Z',
    favoriteMusic: 'Metal',
    favoriteSong: 'Rapture',
    quote:
      'If we back up the alarm, we can get to the SQL sensor through the bluetooth COM bandwidth!',
  },
  {
    firstName: 'Elmer',
    lastName: 'Cummerata',
    address: '184 Katrine Shore',
    state: 'Iowa',
    phoneNumber: '372.603.3205 x712',
    lastLogin: '2021-04-19T11:13:07.667Z',
    favoriteMusic: 'World',
    favoriteSong: 'You Are the Sunshine of My Life',
    quote:
      'If we reboot the sensor, we can get to the VGA port through the mobile SSL alarm!',
  },
  {
    firstName: 'Nella',
    lastName: 'Von',
    address: '1350 Stoltenberg Brooks',
    state: 'Texas',
    phoneNumber: '1-925-845-7429 x0536',
    lastLogin: '2020-03-10T03:40:50.476Z',
    favoriteMusic: 'Jazz',
    favoriteSong: "Theme From 'Greatest American Hero' (Believe It Or Not)",
    quote:
      "You can't input the driver without calculating the online GB bandwidth!",
  },
  {
    firstName: 'Tyler',
    lastName: 'Orn',
    address: '33097 VonRueden Camp',
    state: 'Iowa',
    phoneNumber: '(930) 397-6101',
    lastLogin: '2022-12-31T20:27:01.650Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Secret Love',
    quote:
      'The SMS panel is down, calculate the digital interface so we can calculate the IB program!',
  },
  {
    firstName: 'Joy',
    lastName: 'Lockman',
    address: '3235 Isabell Terrace',
    state: 'Louisiana',
    phoneNumber: '(988) 273-5397 x17397',
    lastLogin: '2021-11-30T23:25:34.134Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'I Got You Babe',
    quote:
      'Use the redundant TCP transmitter, then you can parse the bluetooth matrix!',
  },
  {
    firstName: 'Jarret',
    lastName: 'Kulas',
    address: '364 Gorczany Bypass',
    state: 'Georgia',
    phoneNumber: '1-909-780-0982 x92779',
    lastLogin: '2019-05-27T18:28:31.309Z',
    favoriteMusic: 'Rock',
    favoriteSong: 'Disturbia',
    quote: 'Use the virtual COM port, then you can index the digital driver!',
  },
  {
    firstName: 'Pedro',
    lastName: 'Friesen',
    address: '20032 Waylon Hollow',
    state: 'Indiana',
    phoneNumber: '(268) 387-1965',
    lastLogin: '2022-08-18T16:55:19.848Z',
    favoriteMusic: 'World',
    favoriteSong: 'Up Up & Away',
    quote:
      "You can't calculate the bus without backing up the digital DRAM driver!",
  },
  {
    firstName: 'Dedric',
    lastName: 'Senger',
    address: '818 Borer Dam',
    state: 'Alaska',
    phoneNumber: '1-462-853-3223',
    lastLogin: '2019-12-06T14:14:47.556Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Smoke Gets in Your Eyes',
    quote:
      'The GB sensor is down, synthesize the auxiliary feed so we can input the COM sensor!',
  },
  {
    firstName: 'Jess',
    lastName: 'Powlowski',
    address: '169 Marion Ridges',
    state: 'South Carolina',
    phoneNumber: '445-623-4865 x41525',
    lastLogin: '2020-02-24T19:40:43.679Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Let Me Call You Sweetheart',
    quote:
      'Use the cross-platform DNS bandwidth, then you can transmit the mobile sensor!',
  },
  {
    firstName: 'Herta',
    lastName: 'Schultz',
    address: '46393 Roberta Landing',
    state: 'Minnesota',
    phoneNumber: '798.446.4800',
    lastLogin: '2020-08-19T08:26:34.307Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Hurt So Good',
    quote:
      "I'll connect the cross-platform HDD alarm, that should hard drive the SDD bus!",
  },
  {
    firstName: 'Maurine',
    lastName: 'Boyle',
    address: '243 Wade Point',
    state: 'Arkansas',
    phoneNumber: '1-932-491-9223',
    lastLogin: '2021-11-07T17:38:08.763Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: "Hips don't lie",
    quote: 'We need to connect the redundant ADP system!',
  },
  {
    firstName: 'Marjory',
    lastName: 'McClure',
    address: '350 Cheyanne Camp',
    state: 'West Virginia',
    phoneNumber: '1-413-868-6859 x24987',
    lastLogin: '2023-03-14T18:07:48.268Z',
    favoriteMusic: 'Rap',
    favoriteSong: 'Kiss',
    quote: 'We need to navigate the haptic TLS panel!',
  },
  {
    firstName: 'Darion',
    lastName: 'Wisozk',
    address: '232 Berge Junctions',
    state: 'Arizona',
    phoneNumber: '1-887-450-7810',
    lastLogin: '2023-08-27T12:45:14.167Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'I Get Around',
    quote:
      "transmitting the microchip won't do anything, we need to navigate the cross-platform ADP application!",
  },
  {
    firstName: 'Freda',
    lastName: 'Boyer',
    address: '4092 Lakin Passage',
    state: 'Arizona',
    phoneNumber: '868-901-8673 x19014',
    lastLogin: '2019-01-20T21:51:55.513Z',
    favoriteMusic: 'Non Music',
    favoriteSong: 'Wishing Well',
    quote: 'We need to transmit the back-end RSS capacitor!',
  },
  {
    firstName: 'Daija',
    lastName: 'Cole',
    address: '998 Feil Causeway',
    state: 'Colorado',
    phoneNumber: '591.689.7935',
    lastLogin: '2020-03-29T16:59:21.046Z',
    favoriteMusic: 'World',
    favoriteSong: "(It's No) Sin",
    quote: 'We need to synthesize the redundant SMTP hard drive!',
  },
  {
    firstName: 'Isidro',
    lastName: 'Barton',
    address: '692 Hannah Harbors',
    state: 'Louisiana',
    phoneNumber: '1-521-632-7204',
    lastLogin: '2022-11-02T18:58:59.587Z',
    favoriteMusic: 'Folk',
    favoriteSong: 'Brother',
    quote: 'We need to parse the auxiliary HEX bandwidth!',
  },
  {
    firstName: 'Ada',
    lastName: 'McLaughlin',
    address: '841 Chanelle Canyon',
    state: 'Arkansas',
    phoneNumber: '206.847.6733',
    lastLogin: '2021-03-27T19:56:02.116Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Groove is in the Heart',
    quote: 'We need to reboot the open-source SDD application!',
  },
  {
    firstName: 'Sarah',
    lastName: 'Kuhlman',
    address: '473 Ahmed Knoll',
    state: 'North Carolina',
    phoneNumber: '483-459-2066 x0169',
    lastLogin: '2022-05-27T08:10:57.211Z',
    favoriteMusic: 'Classical',
    favoriteSong: 'I Just Called to Say I Love You',
    quote:
      "compressing the bandwidth won't do anything, we need to bypass the virtual THX capacitor!",
  },
  {
    firstName: 'Branson',
    lastName: 'Boyer',
    address: '0789 Jo Circle',
    state: 'New Mexico',
    phoneNumber: '230.651.5955',
    lastLogin: '2022-08-16T22:49:14.914Z',
    favoriteMusic: 'Stage And Screen',
    favoriteSong: 'Feel Like Making Love',
    quote:
      "I'll copy the virtual PCI application, that should alarm the FTP hard drive!",
  },
  {
    firstName: 'Humberto',
    lastName: 'Beahan',
    address: '16065 Herman Freeway',
    state: 'Washington',
    phoneNumber: '555-464-7388',
    lastLogin: '2020-01-18T15:42:51.572Z',
    favoriteMusic: 'Funk',
    favoriteSong: 'Imagine',
    quote:
      'The PCI hard drive is down, reboot the back-end bandwidth so we can quantify the HEX hard drive!',
  },
  {
    firstName: 'Domenic',
    lastName: 'Bernier',
    address: '83684 Hagenes Crest',
    state: 'New Mexico',
    phoneNumber: '207.846.6268 x29983',
    lastLogin: '2021-06-22T05:33:50.459Z',
    favoriteMusic: 'Latin',
    favoriteSong: 'Philadelphia Freedom',
    quote:
      'The GB monitor is down, program the bluetooth array so we can parse the TLS driver!',
  },
  {
    firstName: 'Alayna',
    lastName: 'Hand',
    address: '51016 Wisozk Grove',
    state: 'New York',
    phoneNumber: '317-783-7334 x538',
    lastLogin: '2023-05-15T18:10:16.387Z',
    favoriteMusic: 'Jazz',
    favoriteSong: 'Yakety Yak',
    quote: 'We need to calculate the multi-byte SCSI circuit!',
  },
  {
    firstName: 'Henri',
    lastName: 'Gottlieb',
    address: '6075 Doyle Tunnel',
    state: 'Colorado',
    phoneNumber: '(691) 295-0631 x8778',
    lastLogin: '2020-11-21T05:57:22.135Z',
    favoriteMusic: 'Electronic',
    favoriteSong: 'Always On My Mind',
    quote:
      'Use the back-end JSON transmitter, then you can parse the virtual sensor!',
  },
];
