name: Clean PR

on:
  pull_request:
    branches:
      - v2

jobs:
  clean-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lint
        run: pnpm run lint -- --fix

      - name: Run Prettier
        run: pnpm format

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'KevinVandy'
          git config --global user.email 'kevinvandy@users.noreply.github.com'
          git add -A
          git commit -m "Lint and Prettier" || exit 0  # in case no changes present
          git push origin ${{ github.head_ref }}
